"""
Configuration for the Telegram Bot — environment, languages, and translations.
"""
import os

from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
OWNER_USERNAME = os.getenv("OWNER_USERNAME")
OWNER_USER_ID = os.getenv("OWNER_USER_ID")
CHANNEL_LINK = os.getenv("CHANNEL_LINK")
PREMIUM_CHANNEL_LINK = os.getenv("PREMIUM_CHANNEL_LINK") or CHANNEL_LINK
EXCHANGE_CHANNEL_LINK = os.getenv("EXCHANGE_CHANNEL_LINK", "https://t.me/+pDSKvonFRf1kMzM1")
EXCHANGE_ADMIN_USERNAME = os.getenv("EXCHANGE_ADMIN_USERNAME", "domeking69")

DEFAULT_LANG = "en"

LANGUAGES = {'en': '🇺🇸 English',
 'es': '🇪🇸 Español',
 'pt': '🇧🇷 Português',
 'de': '🇩🇪 Deutsch',
 'fr': '🇫🇷 Français',
 'it': '🇮🇹 Italiano',
 'ru': '🇷🇺 Русский',
 'ar': '🇸🇦 العربية',
 'hi': '🇮🇳 हिन्दी',
 'tr': '🇹🇷 Türkçe',
 'id': '🇮🇩 Bahasa Indonesia',
 'pl': '🇵🇱 Polski',
 'nl': '🇳🇱 Nederlands',
 'ja': '🇯🇵 日本語',
 'ko': '🇰🇷 한국어',
 'zh': '🇨🇳 中文',
 'uk': '🇺🇦 Українська',
 'vi': '🇻🇳 Tiếng Việt',
 'th': '🇹🇭 ไทย'}

TEXTS = {
    "en":     {
        "language_pick": '🌍 *Language*\n\nSelect your preferred language:',
        "welcome": '👋 *Welcome, {name}!*\n\nFeel free to explore our services at your own pace! We offer a fantastic free experience so you can get a taste of what we have to offer before making any decisions.\n\n🌍 *Choose your language:*',
        "main_menu": '🖤 *Main Menu*\n\nSelect a service to learn and access it:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Discreet · Premium curated experiences\n🎁 *New here?* Start with Free — explore before you commit.',
        "btn_free": '🆓 Free Access',
        "btn_premium_bundles": '💎 Premium & Bundles',
        "btn_exchange": '🔄 Free Exchange Hub',
        "btn_image": '🔞 NSFW Image Morphing',
        "btn_support": '💬 Support',
        "btn_change_lang": '🌍 Language',
        "btn_premium": '👑 Premium',
        "btn_bundles": '📦 Bundles',
        "btn_join_channel": '📢 Join Channel',
        "btn_request_access": '🔑 Request Access',
        "btn_request_membership": '📝 Request Membership',
        "btn_verify_admin": '✅ Verify with Admin',
        "btn_contact_admin": '💬 Contact Admin',
        "btn_back_menu": '◀️ Back to Menu',
        "btn_back_pb": '◀️ Back',
        "free_title": '🆓 *Free Access*',
        "free_body": 'A constantly running site offering fresh new free content nearly every day.\n\nExplore our complimentary collection — curated adult content with no commitment required. Join the channel below and start browsing at your own pace.\n\n✅ No payment required\n✅ Fresh content almost daily\n✅ Discreet & friendly community',
        "premium_title": '👑 *Premium*',
        "premium_body": 'Your all-access pass to the full experience:\n\n💬 *Premium Group Chat* — connect, talk, and stay in the loop\n🔗 *Unlimited Links Forever* — permanent access to everything we score & share in the exchange\n🌐 *Premium Site Pathway* — full access to our curated premium browsing experience\n\n━━━━━━━━━━━━━━━━━━━━\n\nRequest to join the premium channel below.\n\nTo see prices and purchase personally from admin to unlock your access, contact @{owner}.',
        "btn_join_premium": '📺 Request to Join Premium Channel',
        "btn_request_permission": '🔑 Request Permission to Go Premium',
        "bundles_title": '📦 *Premium Bundles*',
        "bundles_body": "📦 *What's included:* Custom-requested content based on your fetishes and fantasies.\n\nWe'll be honest with you — our library is huge, and with a database this size, perfect categorization isn't always easy. Still, we promise to hand-pick and deliver some of the finest content tailored to what *you* ask for.\n\nWe also don't do Mega links or flaky cloud dumps. Those services go offline, links break, and your money goes to waste. What we offer is curated, reliable, and built to last.\n\nTell us what you're looking for — contact our admin below and let's build your bundle together.",
        "btn_request_join_exchange": '📝 Request to Join',
        "btn_verify_exchange_admin": '✅ Verify with Admin',
        "exchange_title": '🔄 *Free Exchange Hub*',
        "exchange_body": "A free community for sharing and *chatting with like-minded people*.\n\nTrade, discuss, and connect with members who share your interests — a space built for genuine exchange and conversation.\n\nCurrently, joining is *approval only*. We want to make sure you have enough to share with the community and that you're respectful to everyone here.\n\nRequest to join the group below, or verify with our exchange admin (@{exchange_admin}).",
        "image_title": '🔞 *NSFW Image Morphing*\n💳 *This is a paid service.*',
        "image_body": "Custom NSFW morphing built around *your* fantasy — any scenario or style you want:\n\n• No dress / fully nude looks\n• Specific positions & poses\n• Outfits, lingerie, or themed dress\n• JOI-style and other personalized requests\n• And more — tell us what you're imagining\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *New service:* We just launched this. Send us one reference photo plus your brief — outfit, pose, setting, vibe — and we'll morph it exactly how you want.\n\nReady to start? Contact our admin below and share your request.",
        "pb_menu": '💎 *Premium & Bundles*\n\nChoose an option below:',
        "help": 'ℹ️ *Help*\n\nUse /start to begin or /menu to return to the main menu.\n\nNeed assistance? Contact @{owner}',
        "notify_premium": '🔔 Premium Access Request',
        "notify_bundles": '🔔 Bundles Access Request',
        "notify_exchange": '🔔 Exchange Hub Membership Request',
        "notify_image": '🔔 NSFW Image Morphing Inquiry',
        "notify_sent": "✅ Your request has been sent. We'll be in touch soon."
    },
    "es":     {
        "language_pick": '🌍 *Idioma*\n\nSelecciona tu idioma preferido:',
        "welcome": '👋 *¡Bienvenido, {name}!*\n\n¡Siéntete libre de explorar nuestros servicios a tu propio ritmo! Ofrecemos una experiencia gratuita fantástica para que conozcas lo que tenemos antes de tomar cualquier decisión.\n\n🌍 *Elige tu idioma:*',
        "main_menu": '🖤 *Menú Principal*\n\nSelecciona un servicio para conocerlo y acceder:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Discreto · Experiencias premium seleccionadas\n🎁 *¿Nuevo aquí?* Empieza con Gratis — explora antes de comprometerte.',
        "btn_free": '🆓 Acceso Gratis',
        "btn_premium_bundles": '💎 Premium y Paquetes',
        "btn_exchange": '🔄 Hub de Intercambio Gratis',
        "btn_image": '🔞 Morphing NSFW',
        "btn_support": '💬 Soporte',
        "btn_change_lang": '🌍 Idioma',
        "btn_premium": '👑 Premium',
        "btn_bundles": '📦 Paquetes',
        "btn_join_channel": '📢 Unirse al Canal',
        "btn_request_access": '🔑 Solicitar Acceso',
        "btn_request_membership": '📝 Solicitar Membresía',
        "btn_verify_admin": '✅ Verificar con Admin',
        "btn_contact_admin": '💬 Contactar Admin',
        "btn_back_menu": '◀️ Volver al Menú',
        "btn_back_pb": '◀️ Atrás',
        "free_title": '🆓 *Acceso Gratis*',
        "free_body": 'Un sitio siempre activo con contenido gratuito nuevo casi todos los días.\n\nExplora nuestra colección gratuita — contenido adulto seleccionado sin compromiso. Únete al canal y empieza a navegar a tu ritmo.\n\n✅ Sin pago requerido\n✅ Contenido fresco casi a diario\n✅ Comunidad discreta y amigable',
        "premium_title": '👑 *Premium*',
        "premium_body": 'Tu pase de acceso total a la experiencia completa:\n\n💬 *Grupo Premium* — chatea, conecta y mantente al día\n🔗 *Enlaces Ilimitados para Siempre* — acceso permanente a todo lo que seleccionamos y compartimos en el exchange\n🌐 *Ruta Premium del Sitio* — acceso completo a la experiencia premium curada\n\n━━━━━━━━━━━━━━━━━━━━\n\nSolicita unirte al canal premium abajo.\n\nPara ver precios y comprar personalmente con el admin para desbloquear tu acceso, contacta @{owner}.',
        "btn_join_premium": '📺 Solicitar Unirse al Canal Premium',
        "btn_request_permission": '🔑 Solicitar Permiso para Premium',
        "bundles_title": '📦 *Paquetes Premium*',
        "bundles_body": '📦 *Qué incluye:* Contenido personalizado según tus fetiches y fantasías.\n\nSeamos honestos — nuestra biblioteca es enorme y, con una base de datos tan grande, categorizar todo a la perfección no siempre es fácil. Aun así, prometemos seleccionar y entregar lo mejor, adaptado a lo que *tú* pidas.\n\nNo usamos enlaces Mega ni nubes poco fiables. Esos servicios caen, los enlaces mueren y tu dinero se pierde. Lo nuestro es curado, fiable y duradero.\n\nCuéntanos qué buscas — contacta al admin abajo y armemos tu paquete juntos.',
        "btn_request_join_exchange": '📝 Solicitar Unirse',
        "btn_verify_exchange_admin": '✅ Verificar con Admin',
        "exchange_title": '🔄 *Hub de Intercambio Gratis*',
        "exchange_body": 'Una comunidad gratuita para compartir y *chatear con personas afines*.\n\nIntercambia, discute y conéctate con miembros que comparten tus intereses.\n\nActualmente, unirse es *solo con aprobación*. Queremos asegurarnos de que tengas suficiente para compartir y que seas respetuoso con todos.\n\nSolicita unirte al grupo abajo, o verifica con nuestro admin de exchange (@{exchange_admin}).',
        "image_title": '🔞 *Morphing de Imágenes NSFW*\n💳 *Este es un servicio de pago.*',
        "image_body": 'Morphing NSFW personalizado según *tu* fantasía — cualquier escenario o estilo:\n\n• Sin ropa / looks desnudos\n• Posiciones y poses específicas\n• Outfits, lencería o vestimenta temática\n• Estilo JOI y otras peticiones personalizadas\n• Y más — cuéntanos qué imaginas\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *Nuevo servicio:* Recién lanzado. Envíanos una foto de referencia más tu brief — outfit, pose, ambiente — y la morfeamos como quieras.\n\n¿Listo? Contacta al admin abajo con tu solicitud.',
        "pb_menu": '💎 *Premium y Paquetes*\n\nElige una opción abajo:',
        "help": 'ℹ️ *Ayuda*\n\nUsa /start para comenzar o /menu para volver al menú principal.\n\n¿Necesitas ayuda? Contacta @{owner}',
        "notify_premium": '🔔 Solicitud de Acceso Premium',
        "notify_bundles": '🔔 Solicitud de Acceso a Paquetes',
        "notify_exchange": '🔔 Solicitud de Membresía al Centro de Intercambio',
        "notify_image": '🔔 Consulta Morphing NSFW',
        "notify_sent": '✅ Tu solicitud ha sido enviada. Nos pondremos en contacto pronto.'
    },
    "pt":     {
        "language_pick": '🌍 *Idioma*\n\nSelecione seu idioma preferido:',
        "welcome": '👋 *Bem-vindo, {name}!*\n\nSinta-se à vontade para explorar nossos serviços no seu ritmo! Oferecemos uma experiência gratuita fantástica para você conhecer o que temos antes de tomar qualquer decisão.\n\n🌍 *Escolha seu idioma:*',
        "main_menu": '🖤 *Menu Principal*\n\nSelecione um serviço para conhecer e acessar:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Discreto · Experiências premium selecionadas\n🎁 *Novo por aqui?* Comece com Grátis — explore antes de se comprometer.',
        "btn_free": '🆓 Acesso Grátis',
        "btn_premium_bundles": '💎 Premium e Pacotes',
        "btn_exchange": '🔄 Hub de Troca Grátis',
        "btn_image": '🔞 Morphing NSFW',
        "btn_support": '💬 Suporte',
        "btn_change_lang": '🌍 Idioma',
        "btn_premium": '👑 Premium',
        "btn_bundles": '📦 Pacotes',
        "btn_join_channel": '📢 Entrar no Canal',
        "btn_request_access": '🔑 Solicitar Acesso',
        "btn_request_membership": '📝 Solicitar Membresia',
        "btn_verify_admin": '✅ Verificar com Admin',
        "btn_contact_admin": '💬 Contatar Admin',
        "btn_back_menu": '◀️ Voltar ao Menu',
        "btn_back_pb": '◀️ Voltar',
        "free_title": '🆓 *Acesso Grátis*',
        "free_body": 'Um site sempre ativo com conteúdo gratuito novo quase todos os dias.\n\nExplore nossa coleção gratuita — conteúdo adulto selecionado sem compromisso. Entre no canal e comece a navegar no seu ritmo.\n\n✅ Sem pagamento\n✅ Conteúdo fresco quase diariamente\n✅ Comunidade discreta e amigável',
        "premium_title": '👑 *Premium*',
        "premium_body": 'Seu passe de acesso total à experiência completa:\n\n💬 *Grupo Premium* — converse, conecte-se e fique por dentro\n🔗 *Links Ilimitados para Sempre* — acesso permanente a tudo que selecionamos e compartilhamos no exchange\n🌐 *Caminho Premium do Site* — acesso completo à experiência premium curada\n\n━━━━━━━━━━━━━━━━━━━━\n\nSolicite entrar no canal premium abaixo.\n\nPara ver preços e comprar pessoalmente com o admin para desbloquear seu acesso, contate @{owner}.',
        "btn_join_premium": '📺 Solicitar Entrada no Canal Premium',
        "btn_request_permission": '🔑 Solicitar Permissão para Premium',
        "bundles_title": '📦 *Pacotes Premium*',
        "bundles_body": '📦 *O que inclui:* Conteúdo personalizado com base nos seus fetiches e fantasias.\n\nVamos ser honestos — nossa biblioteca é enorme e, com um banco de dados desse tamanho, categorizar tudo perfeitamente nem sempre é fácil. Mesmo assim, prometemos selecionar e entregar o melhor, feito para o que *você* pedir.\n\nNão usamos links Mega nem clouds instáveis. Esses serviços caem, links quebram e seu dinheiro vai embora. O que oferecemos é curado, confiável e duradouro.\n\nConte o que procura — fale com o admin abaixo e vamos montar seu pacote juntos.',
        "btn_request_join_exchange": '📝 Solicitar Entrada',
        "btn_verify_exchange_admin": '✅ Verificar com Admin',
        "exchange_title": '🔄 *Hub de Troca Grátis*',
        "exchange_body": 'Uma comunidade gratuita para compartilhar e *conversar com pessoas afins*.\n\nTroque, discuta e conecte-se com membros que compartilham seus interesses.\n\nAtualmente, entrar é *somente com aprovação*. Queremos garantir que você tenha o suficiente para compartilhar e seja respeitoso com todos.\n\nSolicite entrar no grupo abaixo, ou verifique com nosso admin de exchange (@{exchange_admin}).',
        "image_title": '🔞 *Morphing de Imagem NSFW*\n💳 *Este é um serviço pago.*',
        "image_body": 'Morphing NSFW personalizado para *sua* fantasia — qualquer cenário ou estilo:\n\n• Sem roupa / looks nus\n• Posições e poses específicas\n• Roupas, lingerie ou vestimenta temática\n• Estilo JOI e outros pedidos personalizados\n• E mais — conte o que imagina\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *Novo serviço:* Acabamos de lançar. Envie uma foto de referência mais seu brief — roupa, pose, ambiente — e faremos o morph como quiser.\n\nPronto? Fale com o admin abaixo.',
        "pb_menu": '💎 *Premium e Pacotes*\n\nEscolha uma opção abaixo:',
        "help": 'ℹ️ *Ajuda*\n\nUse /start para começar ou /menu para voltar ao menu principal.\n\nPrecisa de ajuda? Contate @{owner}',
        "notify_premium": '🔔 Solicitação de Acesso Premium',
        "notify_bundles": '🔔 Solicitação de Acesso a Pacotes',
        "notify_exchange": '🔔 Solicitação de Membresia no Hub de Troca',
        "notify_image": '🔔 Consulta Morphing NSFW',
        "notify_sent": '✅ Sua solicitação foi enviada. Entraremos em contato em breve.'
    },
    "de":     {
        "language_pick": '🌍 *Sprache*\n\nWähle deine bevorzugte Sprache:',
        "welcome": '👋 *Willkommen, {name}!*\n\nErkunde unsere Services in deinem eigenen Tempo! Wir bieten ein fantastisches Gratis-Erlebnis, damit du einen Eindruck bekommst, bevor du eine Entscheidung triffst.\n\n🌍 *Wähle deine Sprache:*',
        "main_menu": '🖤 *Hauptmenü*\n\nWähle einen Service, um mehr zu erfahren und darauf zuzugreifen:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Diskret · Premium kuratierte Erlebnisse\n🎁 *Neu hier?* Starte mit Gratis — erkunde, bevor du dich entscheidest.',
        "btn_free": '🆓 Gratis-Zugang',
        "btn_premium_bundles": '💎 Premium & Pakete',
        "btn_exchange": '🔄 Gratis Tausch-Hub',
        "btn_image": '🔞 NSFW Bild-Morphing',
        "btn_support": '💬 Support',
        "btn_change_lang": '🌍 Sprache',
        "btn_premium": '👑 Premium',
        "btn_bundles": '📦 Pakete',
        "btn_join_channel": '📢 Kanal beitreten',
        "btn_request_access": '🔑 Zugang anfordern',
        "btn_request_membership": '📝 Mitgliedschaft anfordern',
        "btn_verify_admin": '✅ Mit Admin verifizieren',
        "btn_contact_admin": '💬 Admin kontaktieren',
        "btn_back_menu": '◀️ Zurück zum Menü',
        "btn_back_pb": '◀️ Zurück',
        "free_title": '🆓 *Gratis-Zugang*',
        "free_body": 'Eine dauerhaft laufende Seite mit fast täglich frischen kostenlosen Inhalten.\n\nEntdecke unsere kostenlose Sammlung — kuratierte Inhalte für Erwachsene ohne Verpflichtung. Tritt dem Kanal bei und stöbere in deinem Tempo.\n\n✅ Keine Zahlung\n✅ Fast täglich neue Inhalte\n✅ Diskrete & freundliche Community',
        "premium_title": '👑 *Premium*',
        "premium_body": 'Dein All-Access-Pass für das volle Erlebnis:\n\n💬 *Premium-Gruppenchat* — vernetzen, chatten und informiert bleiben\n🔗 *Unbegrenzte Links für immer* — dauerhafter Zugang zu allem, was wir bewerten & in der Exchange teilen\n🌐 *Premium-Site-Pfad* — voller Zugang zur kuratierten Premium-Erfahrung\n\n━━━━━━━━━━━━━━━━━━━━\n\nFordere unten die Aufnahme in den Premium-Kanal an.\n\nFür Preise und persönlichen Kauf beim Admin kontaktiere @{owner}.',
        "btn_join_premium": '📺 Premium-Kanal Beitritt Anfragen',
        "btn_request_permission": '🔑 Berechtigung für Premium Anfragen',
        "bundles_title": '📦 *Premium-Pakete*',
        "bundles_body": '📦 *Was enthalten ist:* Individuell angefragte Inhalte nach deinen Fetischen und Fantasien.\n\nEhrlich gesagt — unsere Bibliothek ist riesig, und bei einer so großen Datenbank ist perfekte Kategorisierung nicht immer einfach. Trotzdem versprechen wir, das Beste handverlesen für *dich* zu liefern.\n\nKeine Mega-Links oder unzuverlässige Cloud-Dumps. Diese Dienste gehen offline, Links sterben — und dein Geld ist weg. Bei uns bekommst du kuratiert, zuverlässig und nachhaltig.\n\nSag uns, was du suchst — kontaktiere den Admin unten und wir stellen dein Paket zusammen.',
        "btn_request_join_exchange": '📝 Beitritt Anfragen',
        "btn_verify_exchange_admin": '✅ Mit Admin Verifizieren',
        "exchange_title": '🔄 *Gratis Tausch-Hub*',
        "exchange_body": 'Eine kostenlose Community zum Teilen und *Chatten mit Gleichgesinnten*.\n\nTausche, diskutiere und vernetze dich mit Mitgliedern, die deine Interessen teilen.\n\nDerzeit ist der Beitritt *nur mit Genehmigung*. Wir möchten sicherstellen, dass du genug zu teilen hast und respektvoll bist.\n\nFordere unten den Gruppenbeitritt an oder verifiziere dich beim Exchange-Admin (@{exchange_admin}).',
        "image_title": '🔞 *NSFW Bild-Morphing*\n💳 *Dies ist ein kostenpflichtiger Service.*',
        "image_body": 'Individuelles NSFW-Morphing nach *deiner* Fantasie — jedes Szenario oder Stil:\n\n• Ohne Kleidung / nackte Looks\n• Bestimmte Positionen & Posen\n• Outfits, Dessous oder themed Dress\n• JOI-Stil und andere Wünsche\n• Und mehr — sag uns, was du dir vorstellst\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *Neuer Service:* Gerade gestartet. Schick uns ein Referenzfoto plus Briefing — Outfit, Pose, Setting — wir morphen es genau wie du willst.\n\nBereit? Kontaktiere den Admin unten.',
        "pb_menu": '💎 *Premium & Pakete*\n\nWähle eine Option unten:',
        "help": 'ℹ️ *Hilfe*\n\nNutze /start zum Starten oder /menu für das Hauptmenü.\n\nBrauchst du Hilfe? Kontaktiere @{owner}',
        "notify_premium": '🔔 Premium-Zugang angefordert',
        "notify_bundles": '🔔 Paket-Zugang angefordert',
        "notify_exchange": '🔔 Tausch-Hub-Mitgliedschaft angefordert',
        "notify_image": '🔔 NSFW Morphing Anfrage',
        "notify_sent": '✅ Deine Anfrage wurde gesendet. Wir melden uns bald.'
    },
    "fr":     {
        "language_pick": '🌍 *Langue*\n\nSélectionnez votre langue préférée :',
        "welcome": '👋 *Bienvenue, {name}!*\n\nExplorez nos services à votre rythme ! Nous offrons une expérience gratuite fantastique pour découvrir ce que nous proposons avant de vous engager.\n\n🌍 *Choisissez votre langue :*',
        "main_menu": '🖤 *Menu Principal*\n\nSélectionnez un service pour le découvrir et y accéder :',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Discret · Expériences premium sélectionnées\n🎁 *Nouveau ici ?* Commencez par Gratuit — explorez avant de vous engager.',
        "btn_free": '🆓 Accès Gratuit',
        "btn_premium_bundles": '💎 Premium & Forfaits',
        "btn_exchange": "🔄 Hub d'Échange Gratuit",
        "btn_image": '🔞 Morphing NSFW',
        "btn_support": '💬 Support',
        "btn_change_lang": '🌍 Langue',
        "btn_premium": '👑 Premium',
        "btn_bundles": '📦 Forfaits',
        "btn_join_channel": '📢 Rejoindre le Canal',
        "btn_request_access": "🔑 Demander l'Accès",
        "btn_request_membership": "📝 Demander l'Adhésion",
        "btn_verify_admin": '✅ Vérifier avec Admin',
        "btn_contact_admin": '💬 Contacter Admin',
        "btn_back_menu": '◀️ Retour au Menu',
        "btn_back_pb": '◀️ Retour',
        "free_title": '🆓 *Accès Gratuit*',
        "free_body": 'Un site en continu avec du contenu gratuit frais presque chaque jour.\n\nExplorez notre collection gratuite — contenu adulte sélectionné sans engagement. Rejoignez le canal et parcourez à votre rythme.\n\n✅ Aucun paiement requis\n✅ Contenu frais presque quotidien\n✅ Communauté discrète et conviviale',
        "premium_title": '👑 *Premium*',
        "premium_body": "Votre pass accès total à l'expérience complète :\n\n💬 *Groupe Premium* — discutez, connectez-vous et restez informé\n🔗 *Liens Illimités à Vie* — accès permanent à tout ce que nous sélectionnons et partageons\n🌐 *Parcours Premium du Site* — accès complet à l'expérience premium curatée\n\n━━━━━━━━━━━━━━━━━━━━\n\nDemandez à rejoindre le canal premium ci-dessous.\n\nPour voir les prix et acheter personnellement auprès de l'admin, contactez @{owner}.",
        "btn_join_premium": '📺 Demander à Rejoindre le Canal Premium',
        "btn_request_permission": '🔑 Demander la Permission Premium',
        "bundles_title": '📦 *Forfaits Premium*',
        "bundles_body": "📦 *Ce qui est inclus :* Contenu sur demande selon vos fétiches et fantasmes.\n\nSoyons honnêtes — notre bibliothèque est immense et, avec une base aussi vaste, tout catégoriser parfaitement n'est pas toujours facile. Nous promettons quand même de sélectionner et livrer le meilleur, adapté à *vos* demandes.\n\nPas de liens Mega ni de dumps cloud instables. Ces services tombent, les liens meurent et votre argent est perdu. Nous proposons du contenu curaté, fiable et durable.\n\nDites-nous ce que vous cherchez — contactez l'admin ci-dessous pour créer votre forfait.",
        "btn_request_join_exchange": '📝 Demander à Rejoindre',
        "btn_verify_exchange_admin": "✅ Vérifier avec l'Admin",
        "exchange_title": "🔄 *Hub d'Échange Gratuit*",
        "exchange_body": "Une communauté gratuite pour partager et *discuter avec des personnes partageant les mêmes idées*.\n\nÉchangez, discutez et connectez-vous avec des membres qui partagent vos intérêts.\n\nActuellement, l'adhésion est *sur approbation uniquement*. Nous voulons nous assurer que vous avez assez à partager et que vous êtes respectueux.\n\nDemandez à rejoindre le groupe ci-dessous, ou vérifiez avec notre admin exchange (@{exchange_admin}).",
        "image_title": "🔞 *Morphing d'Images NSFW*\n💳 *Il s'agit d'un service payant.*",
        "image_body": "Morphing NSFW sur mesure selon *votre* fantasme — tout scénario ou style:\n\n• Sans vêtements / looks nus\n• Positions et poses spécifiques\n• Tenues, lingerie ou dress thématique\n• Style JOI et autres demandes personnalisées\n• Et plus — dites-nous ce que vous imaginez\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *Nouveau service :* Vient d'être lancé. Envoyez une photo de référence plus votre brief — tenue, pose, ambiance — on la morphe comme vous voulez.\n\nPrêt ? Contactez l'admin ci-dessous.",
        "pb_menu": '💎 *Premium & Forfaits*\n\nChoisissez une option ci-dessous :',
        "help": "ℹ️ *Aide*\n\nUtilisez /start pour commencer ou /menu pour revenir au menu principal.\n\nBesoin d'aide ? Contactez @{owner}",
        "notify_premium": "🔔 Demande d'Accès Premium",
        "notify_bundles": "🔔 Demande d'Accès aux Forfaits",
        "notify_exchange": "🔔 Demande d'Adhésion au Hub d'Échange",
        "notify_image": '🔔 Demande Morphing NSFW',
        "notify_sent": '✅ Votre demande a été envoyée. Nous vous contacterons bientôt.'
    },
    "it":     {
        "language_pick": '🌍 *Lingua*\n\nSeleziona la tua lingua preferita:',
        "welcome": "👋 *Benvenuto, {name}!*\n\nEsplora i nostri servizi al tuo ritmo! Offriamo un'esperienza gratuita fantastica per scoprire cosa abbiamo da offrire prima di prendere qualsiasi decisione.\n\n🌍 *Scegli la tua lingua:*",
        "main_menu": '🖤 *Menu Principale*\n\nSeleziona un servizio per scoprirlo e accedervi:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Discreto · Esperienze premium selezionate\n🎁 *Nuovo qui?* Inizia con Gratis — esplora prima di impegnarti.',
        "btn_free": '🆓 Accesso Gratuito',
        "btn_premium_bundles": '💎 Premium e Pacchetti',
        "btn_exchange": '🔄 Hub di Scambio Gratuito',
        "btn_image": '🔞 Morphing NSFW',
        "btn_support": '💬 Supporto',
        "btn_change_lang": '🌍 Lingua',
        "btn_premium": '👑 Premium',
        "btn_bundles": '📦 Pacchetti',
        "btn_join_channel": '📢 Unisciti al Canale',
        "btn_request_access": '🔑 Richiedi Accesso',
        "btn_request_membership": '📝 Richiedi Iscrizione',
        "btn_verify_admin": '✅ Verifica con Admin',
        "btn_contact_admin": '💬 Contatta Admin',
        "btn_back_menu": '◀️ Torna al Menu',
        "btn_back_pb": '◀️ Indietro',
        "free_title": '🆓 *Accesso Gratuito*',
        "free_body": 'Un sito sempre attivo con nuovi contenuti gratuiti quasi ogni giorno.\n\nEsplora la nostra collezione gratuita — contenuti per adulti selezionati senza impegno. Unisciti al canale e inizia a navigare con calma.\n\n✅ Nessun pagamento\n✅ Contenuti freschi quasi ogni giorno\n✅ Community discreta e amichevole',
        "premium_title": '👑 *Premium*',
        "premium_body": "Il tuo pass accesso totale all'esperienza completa:\n\n💬 *Gruppo Premium* — chatta, connettiti e resta aggiornato\n🔗 *Link Illimitati per Sempre* — accesso permanente a tutto ciò che selezioniamo e condividiamo\n🌐 *Percorso Premium del Sito* — accesso completo all'esperienza premium curata\n\n━━━━━━━━━━━━━━━━━━━━\n\nRichiedi di unirti al canale premium qui sotto.\n\nPer prezzi e acquisto personale dall'admin, contatta @{owner}.",
        "btn_join_premium": '📺 Richiedi di Unirti al Canale Premium',
        "btn_request_permission": '🔑 Richiedi Permesso Premium',
        "bundles_title": '📦 *Pacchetti Premium*',
        "bundles_body": "📦 *Cosa include:* Contenuti personalizzati in base ai tuoi feticci e fantasie.\n\nSiamo onesti — la nostra libreria è enorme e, con un database così grande, categorizzare tutto perfettamente non è sempre facile. Promettiamo comunque di selezionare e consegnare il meglio, su misura per *te*.\n\nNiente link Mega o cloud inaffidabili. Quei servizi vanno offline, i link muoiono e i tuoi soldi spariscono. Noi offriamo contenuti curati, affidabili e duraturi.\n\nDicci cosa cerchi — contatta l'admin qui sotto e creiamo il tuo pacchetto insieme.",
        "btn_request_join_exchange": '📝 Richiedi di Unirti',
        "btn_verify_exchange_admin": '✅ Verifica con Admin',
        "exchange_title": '🔄 *Hub di Scambio Gratuito*',
        "exchange_body": "Una community gratuita per condividere e *chattare con persone affini*.\n\nScambia, discuti e connettiti con membri che condividono i tuoi interessi.\n\nAttualmente l'iscrizione è *solo su approvazione*. Vogliamo assicurarci che tu abbia abbastanza da condividere e che tu sia rispettoso.\n\nRichiedi di unirti al gruppo qui sotto, o verifica con il nostro admin exchange (@{exchange_admin}).",
        "image_title": '🔞 *Morphing Immagini NSFW*\n💳 *Questo è un servizio a pagamento.*',
        "image_body": "Morphing NSFW personalizzato per la *tua* fantasia — qualsiasi scenario o stile:\n\n• Senza vestiti / look nudi\n• Posizioni e pose specifiche\n• Outfit, lingerie o abiti tematici\n• Stile JOI e altre richieste personalizzate\n• E altro — raccontaci cosa immagini\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *Nuovo servizio:* Appena lanciato. Invia una foto di riferimento più il brief — outfit, posa, setting — e la morpheremo come vuoi.\n\nPronto? Contatta l'admin qui sotto.",
        "pb_menu": "💎 *Premium e Pacchetti*\n\nScegli un'opzione qui sotto:",
        "help": 'ℹ️ *Aiuto*\n\nUsa /start per iniziare o /menu per tornare al menu principale.\n\nHai bisogno di aiuto? Contatta @{owner}',
        "notify_premium": '🔔 Richiesta Accesso Premium',
        "notify_bundles": '🔔 Richiesta Accesso Pacchetti',
        "notify_exchange": '🔔 Richiesta Iscrizione Hub di Scambio',
        "notify_image": '🔔 Richiesta Morphing NSFW',
        "notify_sent": '✅ La tua richiesta è stata inviata. Ti contatteremo presto.'
    },
    "ru":     {
        "language_pick": '🌍 *Язык*\n\nВыберите предпочитаемый язык:',
        "welcome": '👋 *Добро пожаловать, {name}!*\n\nИсследуйте наши сервисы в своём темпе! Мы предлагаем отличный бесплатный опыт, чтобы вы могли оценить наши возможности перед принятием решения.\n\n🌍 *Выберите язык:*',
        "main_menu": '🖤 *Главное меню*\n\nВыберите сервис, чтобы узнать о нём и получить доступ:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Конфиденциально · Премиальный отбор контента\n🎁 *Впервые здесь?* Начните с Бесплатного — изучите, прежде чем решаться.',
        "btn_free": '🆓 Бесплатный доступ',
        "btn_premium_bundles": '💎 Премиум и Пакеты',
        "btn_exchange": '🔄 Бесплатный Хаб Обмена',
        "btn_image": '🔞 NSFW Морфинг',
        "btn_support": '💬 Поддержка',
        "btn_change_lang": '🌍 Язык',
        "btn_premium": '💎 Премиум',
        "btn_bundles": '📦 Пакеты',
        "btn_join_channel": '📢 Вступить в Канал',
        "btn_request_access": '🔑 Запросить Доступ',
        "btn_request_membership": '📝 Запросить Членство',
        "btn_verify_admin": '✅ Подтвердить у Админа',
        "btn_contact_admin": '💬 Связаться с Админом',
        "btn_back_menu": '◀️ В главное меню',
        "btn_back_pb": '◀️ Назад',
        "free_title": '🆓 *Бесплатный доступ*',
        "free_body": 'Постоянно работающий сайт с новым бесплатным контентом почти каждый день.\n\nИзучите нашу бесплатную коллекцию — отборный контент для взрослых без обязательств. Присоединяйтесь к каналу и просматривайте в своём темпе.\n\n✅ Без оплаты\n✅ Свежий контент почти ежедневно\n✅ Конфиденциальное сообщество',
        "premium_title": '👑 *Премиум*',
        "premium_body": 'Полный доступ ко всему опыту:\n\n💬 *Премиум-группа* — общайтесь и будьте в курсе\n🔗 *Безлимитные ссылки навсегда* — постоянный доступ ко всему из exchange\n🌐 *Премиум-путь на сайте* — полный доступ к премиум-опыту\n\n━━━━━━━━━━━━━━━━━━━━\n\nЗапросите вступление в премиум-канал ниже.\n\nЦены и личная покупка у админа — напишите @{owner}.',
        "btn_join_premium": '📺 Запрос на Вступление в Премиум-канал',
        "btn_request_permission": '🔑 Запросить Разрешение на Premium',
        "bundles_title": '📦 *Премиум Пакеты*',
        "bundles_body": '📦 *Что входит:* Индивидуальный контент по вашим фетишам и фантазиям.\n\nЧестно говоря — наша библиотека огромна, и при такой базе идеальная категоризация не всегда возможна. Но мы обещаем отобрать и доставить лучшее под *ваши* запросы.\n\nМы не используем Mega-ссылки и ненадёжные облака. Сервисы падают, ссылки умирают — и ваши деньги пропадают. У нас — курируемый, надёжный контент.\n\nРасскажите, что ищете — напишите админу ниже, и соберём ваш пакет вместе.',
        "btn_request_join_exchange": '📝 Запрос на Вступление',
        "btn_verify_exchange_admin": '✅ Подтвердить у Админа',
        "exchange_title": '🔄 *Бесплатный Хаб Обмена*',
        "exchange_body": 'Бесплатное сообщество для обмена и *общения с единомышленниками*.\n\nОбменивайтесь, обсуждайте и общайтесь с участниками, разделяющими ваши интересы.\n\nСейчас вступление *только по одобрению*. Мы хотим убедиться, что у вас есть чем поделиться и вы уважительны к сообществу.\n\nЗапросите вступление в группу ниже или свяжитесь с админом exchange (@{exchange_admin}).',
        "image_title": '🔞 *NSFW Морфинг Изображений*\n💳 *Это платный сервис.*',
        "image_body": 'Индивидуальный NSFW-морфинг под *вашу* фантазию — любой сценарий или стиль:\n\n• Без одежды / обнажённые образы\n• Конкретные позы и положения\n• Наряды, бельё или тематическая одежда\n• JOI и другие персональные запросы\n• И больше — опишите, что представляете\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *Новый сервис:* Только запустили. Пришлите референс-фото и описание — наряд, поза, обстановка — и мы сделаем морфинг как вы хотите.\n\nГотовы? Напишите админу ниже.',
        "pb_menu": '💎 *Премиум и Пакеты*\n\nВыберите вариант ниже:',
        "help": 'ℹ️ *Помощь*\n\nИспользуйте /start для начала или /menu для возврата в главное меню.\n\nНужна помощь? Свяжитесь @{owner}',
        "notify_premium": '🔔 Запрос Премиум Доступа',
        "notify_bundles": '🔔 Запрос Доступа к Пакетам',
        "notify_exchange": '🔔 Запрос Членства в Обменном Хабе',
        "notify_image": '🔔 Запрос NSFW Морфинг',
        "notify_sent": '✅ Ваш запрос отправлен. Мы скоро свяжемся с вами.'
    },
    "ar":     {
        "language_pick": '🌍 *اللغة*\n\nاختر لغتك المفضلة:',
        "welcome": '👋 *مرحباً، {name}!*\n\nلا تتردد في استكشاف خدماتنا على راحتك! نقدم تجربة مجانية رائعة لتتعرف على ما نقدمه قبل اتخاذ أي قرار.\n\n🌍 *اختر لغتك:*',
        "main_menu": '🖤 *القائمة الرئيسية*\n\nاختر خدمة للتعرف عليها والوصول إليها:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · سري · تجارب مميزة مختارة\n🎁 *جديد هنا؟* ابدأ بالمجاني — استكشف قبل الالتزام.',
        "btn_free": '🆓 وصول مجاني',
        "btn_premium_bundles": '💎 بريميوم وحزم',
        "btn_exchange": '🔄 مركز التبادل المجاني',
        "btn_image": '🔞 تحويل NSFW',
        "btn_support": '💬 الدعم',
        "btn_change_lang": '🌍 اللغة',
        "btn_premium": '💎 بريميوم',
        "btn_bundles": '📦 حزم',
        "btn_join_channel": '📢 انضم للقناة',
        "btn_request_access": '🔑 طلب الوصول',
        "btn_request_membership": '📝 طلب العضوية',
        "btn_verify_admin": '✅ التحقق مع المسؤول',
        "btn_contact_admin": '💬 تواصل مع المسؤول',
        "btn_back_menu": '◀️ العودة للقائمة',
        "btn_back_pb": '◀️ رجوع',
        "free_title": '🆓 *وصول مجاني*',
        "free_body": 'موقع يعمل باستمرار مع محتوى مجاني جديد تقريباً كل يوم.\n\nاستكشف مجموعتنا المجانية — محتوى للبالغين بدون أي التزام. انضم للقناة وابدأ التصفح بالوتيرة التي تناسبك.\n\n✅ بدون دفع\n✅ محتوى جديد تقريباً يومياً\n✅ مجتمع سري وودود',
        "premium_title": '👑 *بريميوم*',
        "premium_body": 'تصريحك للوصول الكامل:\n\n💬 *مجموعة بريميوم* — تواصل وابقَ على اطلاع\n🔗 *روابط غير محدودة للأبد* — وصول دائم لكل ما نختاره ونشاركه\n🌐 *مسار الموقع البريميوم* — وصول كامل للتجربة المميزة\n\n━━━━━━━━━━━━━━━━━━━━\n\nاطلب الانضمام لقناة البريميوم أدناه.\n\nلمعرفة الأسعار والشراء شخصياً من الأدمن، تواصل مع @{owner}.',
        "btn_join_premium": '📺 طلب الانضمام لقناة البريميوم',
        "btn_request_permission": '🔑 طلب الإذن للبريميوم',
        "bundles_title": '📦 *حزم بريميوم*',
        "bundles_body": '📦 *ما يشمل:* محتوى مخصص حسب fetishes و fantasies الخاصة بك.\n\nبصراحة — مكتبتنا ضخمة، ومع قاعدة بيانات بهذا الحجم، التصنيف المثالي ليس دائماً سهلاً. لكننا نعد باختيار وتقديم الأفضل حسب *طلبك*.\n\nلا نستخدم روابط Mega أو تخزين سحابي غير موثوق. تلك الخدمات تتعطل والروابط تموت وتضيع أموالك. ما نقدمه مُختار بعناية وموثوق.\n\nأخبرنا بما تبحث عنه — تواصل مع الأدمن أدناه لنبني حزمتك معاً.',
        "btn_request_join_exchange": '📝 طلب الانضمام',
        "btn_verify_exchange_admin": '✅ التحقق مع الأدمن',
        "exchange_title": '🔄 *مركز التبادل المجاني*',
        "exchange_body": 'مجتمع مجاني للمشاركة و*الدردشة مع أشخاص يشاركونك اهتماماتك*.\n\nتبادل، ناقش وتواصل مع الأعضاء الذين يشاركونك اهتماماتك.\n\nحالياً، الانضمام *بالموافقة فقط*. نريد التأكد من أن لديك ما يكفي للمشاركة وأنك محترم مع الجميع.\n\nاطلب الانضمام للمجموعة أدناه، أو تحقق مع admin التبادل (@{exchange_admin}).',
        "image_title": '🔞 *تحويل صور NSFW*\n💳 *هذه خدمة مدفوعة.*',
        "image_body": 'تحويل NSFW مخصص حسب *خيالك* — أي سينario أو أسلوب:\n\n• بدون ملابس / مظهر عاري\n• أوضاع ووضعيات محددة\n• أزياء، lingerie أو ملابس themed\n• أسلوب JOI وطلبات مخصصة أخرى\n• والمزيد — أخبرنا بما تتخيل\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *خدمة جديدة:* أطلقناها للتو. أرسل صورة مرجعية مع وصفك — الملابس، الوضعية، الأجواء — وسنحولها كما تريد.\n\nمستعد؟ تواصل مع الأدمن أدناه.',
        "pb_menu": '💎 *بريميوم وحزم*\n\nاختر خياراً أدناه:',
        "help": 'ℹ️ *مساعدة*\n\nاستخدم /start للبدء أو /menu للعودة للقائمة الرئيسية.\n\nتحتاج مساعدة؟ تواصل @{owner}',
        "notify_premium": '🔔 طلب وصول بريميوم',
        "notify_bundles": '🔔 طلب وصول للحزم',
        "notify_exchange": '🔔 طلب عضوية مركز التبادل',
        "notify_image": '🔔 استفسار تحويل NSFW',
        "notify_sent": '✅ تم إرسال طلبك. سنتواصل معك قريباً.'
    },
    "hi":     {
        "language_pick": '🌍 *भाषा*\n\nअपनी पसंदीदा भाषा चुनें:',
        "welcome": '👋 *स्वागत है, {name}!*\n\nअपनी गति से हमारी सेवाएँ explore करें! हम एक शानदार मुफ़्त अनुभव देते हैं ताकि आप निर्णय लेने से पहले हमारी पेशकश का अनुभव कर सकें।\n\n🌍 *अपनी भाषा चुनें:*',
        "main_menu": '🖤 *मुख्य मेनू*\n\nकिसी सेवा को जानने और उस तक पहुँचने के लिए चुनें:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · गोपनीय · प्रीमियम curated अनुभव\n🎁 *नए हैं?* Free से शुरू करें — commit करने से पहले explore करें।',
        "btn_free": '🆓 मुफ़्त एक्सेस',
        "btn_premium_bundles": '💎 प्रीमियम और बंडल',
        "btn_exchange": '🔄 मुफ़्त Exchange Hub',
        "btn_image": '🔞 NSFW Image Morphing',
        "btn_support": '💬 सहायता',
        "btn_change_lang": '🌍 भाषा',
        "btn_premium": '💎 प्रीमियम',
        "btn_bundles": '📦 बंडल',
        "btn_join_channel": '📢 चैनल जॉइन करें',
        "btn_request_access": '🔑 एक्सेस का अनुरोध',
        "btn_request_membership": '📝 सदस्यता का अनुरोध',
        "btn_verify_admin": '✅ एडमिन से सत्यापित करें',
        "btn_contact_admin": '💬 एडमिन से संपर्क',
        "btn_back_menu": '◀️ मेनू पर वापस',
        "btn_back_pb": '◀️ वापस',
        "free_title": '🆓 *मुफ़्त एक्सेस*',
        "free_body": 'लगभग हर दिन नया मुफ़्त कंटेंट देने वाली लगातार चलने वाली साइट।\n\nहमारा मुफ़्त संग्रह देखें — बिना किसी प्रतिबद्धता के क्यूरेटेड adult कंटेंट। चैनल जॉइन करें और अपनी गति से ब्राउज़ करें।\n\n✅ कोई भुगतान नहीं\n✅ लगभग रोज़ नया कंटेंट\n✅ गोपनीय और मित्रवत समुदाय',
        "premium_title": '👑 *प्रीमियम*',
        "premium_body": 'पूरे अनुभव के लिए आपका ऑल-एक्सेस पास:\n\n💬 *प्रीमियम ग्रुप चैट* — जुड़ें और अपडेट रहें\n🔗 *हमेशा के लिए असीमित लिंक* — exchange की स्थायी पहुँच\n🌐 *प्रीमियम साइट पाथवे* — पूरा प्रीमियम एक्सेस\n\n━━━━━━━━━━━━━━━━━━━━\n\nनीचे प्रीमियम चैनल join करने का अनुरोध करें।\n\nकीमतें और admin से व्यक्तिगत खरीद के लिए @{owner} से संपर्क करें।',
        "btn_join_premium": '📺 प्रीमियम चैनल Join का अनुरोध',
        "btn_request_permission": '🔑 प्रीमियम की अनुमति माँगें',
        "bundles_title": '📦 *प्रीमियम बंडल*',
        "bundles_body": '📦 *शामिल है:* आपकी fetishes और fantasies के अनुसार custom कंटेंट।\n\nसच कहें — हमारी library बहुत बड़ी है, और इतने database में perfect categorization हमेशा आसान नहीं। फिर भी, *आपकी* request के अनुसार बेहतरीन चुनकर deliver करने का वादा करते हैं।\n\nMega links या unreliable cloud dumps हम use नहीं करते। वे offline हो जाते हैं, links टूटते हैं और आपका पैसा बर्बाद। हम curated, reliable delivery देते हैं।\n\nबताएँ क्या चाहिए — नीचे admin से contact करें, साथ मिलकर bundle बनाते हैं।',
        "btn_request_join_exchange": '📝 Join का अनुरोध',
        "btn_verify_exchange_admin": '✅ Admin से Verify करें',
        "exchange_title": '🔄 *मुफ़्त Exchange Hub*',
        "exchange_body": 'साझा करने और *समान सोच वाले लोगों से chat* करने के लिए एक मुफ़्त community।\n\nअपने interests साझा करने वाले members के साथ जुड़ें, चर्चा करें और exchange करें।\n\nअभी joining *केवल approval पर* है। हम यह सुनिश्चित करना चाहते हैं कि आपके पास share करने के लिए पर्याप्त है और आप सभी के प्रति respectful हैं।\n\nनीचे group join का request करें, या exchange admin (@{exchange_admin}) से verify करें।',
        "image_title": '🔞 *NSFW Image Morphing*\n💳 *यह एक paid service है।*',
        "image_body": '*आपकी* fantasy के अनुसार custom NSFW morphing — कोई भी scenario या style:\n\n• No dress / nude looks\n• Specific positions & poses\n• Outfits, lingerie, themed dress\n• JOI-style और personalized requests\n• और भी — बताएँ क्या imagine करते हैं\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *नई service:* अभी launch हुई। एक reference photo + brief भेजें — outfit, pose, setting — हम exactly वैसा morph करेंगे।\n\nतैयार? नीचे admin से contact करें।',
        "pb_menu": '💎 *प्रीमियम और बंडल*\n\nनीचे एक विकल्प चुनें:',
        "help": 'ℹ️ *सहायता*\n\nशुरू करने के लिए /start या main menu पर वापस /menu का उपयोग करें।\n\nमदद चाहिए? @{owner} से contact करें',
        "notify_premium": '🔔 प्रीमियम एक्सेस अनुरोध',
        "notify_bundles": '🔔 बंडल एक्सेस अनुरोध',
        "notify_exchange": '🔔 एक्सचेंज हब सदस्यता अनुरोध',
        "notify_image": '🔔 NSFW Morphing Inquiry',
        "notify_sent": '✅ आपका अनुरोध भेज दिया गया है। हम जल्द संपर्क करेंगे।'
    },
    "tr":     {
        "language_pick": '🌍 *Dil*\n\nTercih ettiğin dili seç:',
        "welcome": '👋 *Hoş geldin, {name}!*\n\nHizmetlerimizi kendi hızında keşfet! Karar vermeden önce neler sunduğumuzu deneyimlemen için harika bir ücretsiz deneyim sunuyoruz.\n\n🌍 *Dilini seç:*',
        "main_menu": '🖤 *Ana Menü*\n\nBir hizmeti öğrenmek ve erişmek için seç:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Gizli · Premium seçilmiş deneyimler\n🎁 *Yeni misin?* Ücretsiz ile başla — karar vermeden önce keşfet.',
        "btn_free": '🆓 Ücretsiz Erişim',
        "btn_premium_bundles": '💎 Premium ve Paketler',
        "btn_exchange": '🔄 Ücretsiz Takas Merkezi',
        "btn_image": '🔞 NSFW Görsel Morphing',
        "btn_support": '💬 Destek',
        "btn_change_lang": '🌍 Dil',
        "btn_premium": '👑 Premium',
        "btn_bundles": '📦 Paketler',
        "btn_join_channel": '📢 Kanala Katıl',
        "btn_request_access": '🔑 Erişim İste',
        "btn_request_membership": '📝 Üyelik İste',
        "btn_verify_admin": '✅ Admin ile Doğrula',
        "btn_contact_admin": '💬 Admin ile İletişim',
        "btn_back_menu": '◀️ Menüye Dön',
        "btn_back_pb": '◀️ Geri',
        "free_title": '🆓 *Ücretsiz Erişim*',
        "free_body": 'Neredeyse her gün yeni ücretsiz içerik sunan sürekli çalışan bir site.\n\nÜcretsiz koleksiyonumuzu keşfedin — taahhütsüz, seçilmiş yetişkin içeriği. Kanala katılın ve kendi hızınızda gezinin.\n\n✅ Ödeme yok\n✅ Neredeyse her gün taze içerik\n✅ Gizli ve samimi topluluk',
        "premium_title": '👑 *Premium*',
        "premium_body": "Tam deneyim için all-access pass'iniz:\n\n💬 *Premium Grup Sohbeti* — bağlanın ve güncel kalın\n🔗 *Sonsuza Kadar Sınırsız Linkler* — exchange'deki kalıcı erişim\n🌐 *Premium Site Yolu* — tam premium erişim\n\n━━━━━━━━━━━━━━━━━━━━\n\nAşağıdan premium kanala katılma talebinde bulunun.\n\nFiyatlar ve admin'den kişisel satın alma için @{owner} ile iletişime geçin.",
        "btn_join_premium": '📺 Premium Kanala Katılma Talebi',
        "btn_request_permission": '🔑 Premium İzni İste',
        "bundles_title": '📦 *Premium Paketler*',
        "bundles_body": "📦 *Dahil olan:* Fetişlerinize ve fantezilerinize göre özel içerik.\n\nDürüst olalım — kütüphanemiz devasa ve bu kadar büyük bir veritabanında mükemmel kategorileme her zaman kolay değil. Yine de *sizin* isteklerinize göre en iyisini seçip teslim etmeyi vaat ediyoruz.\n\nMega linkler veya güvenilmez cloud dump'lar kullanmıyoruz. Servisler kapanır, linkler ölür ve paranız boşa gider. Bizim sunduğumuz küratörlü, güvenilir ve kalıcı.\n\nNe aradığınızı söyleyin — aşağıdan admin ile iletişime geçin, paketinizi birlikte oluşturalım.",
        "btn_request_join_exchange": '📝 Katılma Talebi',
        "btn_verify_exchange_admin": '✅ Admin ile Doğrula',
        "exchange_title": '🔄 *Ücretsiz Takas Merkezi*',
        "exchange_body": 'Paylaşım ve *benzer düşünen insanlarla sohbet* için ücretsiz bir topluluk.\n\nİlgi alanlarını paylaşan üyelerle takas edin, tartışın ve bağlantı kurun.\n\nŞu anda katılım *yalnızca onayla*. Paylaşacak yeterli içeriğiniz olduğundan ve herkese saygılı olduğunuzdan emin olmak istiyoruz.\n\nAşağıdan gruba katılma talebinde bulunun veya exchange admin (@{exchange_admin}) ile doğrulayın.',
        "image_title": '🔞 *NSFW Görsel Morphing*\n💳 *Bu ücretli bir hizmettir.*',
        "image_body": '*Fantezinize* göre özel NSFW morphing — her senaryo veya stil:\n\n• Kıyafetsiz / çıplak görünümler\n• Belirli pozisyonlar\n• Kıyafet, iç çamaşırı veya temalı giyim\n• JOI tarzı ve kişisel istekler\n• Ve daha fazlası — hayal ettiğinizi söyleyin\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *Yeni hizmet:* Yeni başladık. Bir referans fotoğraf ve brief gönderin — kıyafet, poz, ortam — istediğiniz gibi morph edelim.\n\nHazır mısınız? Aşağıdan admin ile iletişime geçin.',
        "pb_menu": '💎 *Premium ve Paketler*\n\nAşağıdan bir seçenek seç:',
        "help": 'ℹ️ *Yardım*\n\nBaşlamak için /start veya ana menüye dönmek için /menu kullan.\n\nYardıma mı ihtiyacın var? @{owner} ile iletişime geç',
        "notify_premium": '🔔 Premium Erişim Talebi',
        "notify_bundles": '🔔 Paket Erişim Talebi',
        "notify_exchange": '🔔 Takas Merkezi Üyelik Talebi',
        "notify_image": '🔔 NSFW Morphing Talebi',
        "notify_sent": '✅ Talebin gönderildi. Yakında sizinle iletişime geçeceğiz.'
    },
    "id":     {
        "language_pick": '🌍 *Bahasa*\n\nPilih bahasa pilihanmu:',
        "welcome": '👋 *Selamat datang, {name}!*\n\nJelajahi layanan kami sesuai kecepatanmu! Kami menawarkan pengalaman gratis yang fantastis agar kamu bisa merasakan apa yang kami tawarkan sebelum memutuskan.\n\n🌍 *Pilih bahasamu:*',
        "main_menu": '🖤 *Menu Utama*\n\nPilih layanan untuk mempelajari dan mengaksesnya:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Rahasia · Pengalaman premium pilihan\n🎁 *Baru di sini?* Mulai dengan Gratis — jelajahi sebelum berkomitmen.',
        "btn_free": '🆓 Akses Gratis',
        "btn_premium_bundles": '💎 Premium & Paket',
        "btn_exchange": '🔄 Hub Tukar Gratis',
        "btn_image": '🔞 Morphing NSFW',
        "btn_support": '💬 Dukungan',
        "btn_change_lang": '🌍 Bahasa',
        "btn_premium": '👑 Premium',
        "btn_bundles": '📦 Paket',
        "btn_join_channel": '📢 Gabung Kanal',
        "btn_request_access": '🔑 Minta Akses',
        "btn_request_membership": '📝 Minta Keanggotaan',
        "btn_verify_admin": '✅ Verifikasi dengan Admin',
        "btn_contact_admin": '💬 Hubungi Admin',
        "btn_back_menu": '◀️ Kembali ke Menu',
        "btn_back_pb": '◀️ Kembali',
        "free_title": '🆓 *Akses Gratis*',
        "free_body": 'Situs yang terus berjalan dengan konten gratis baru hampir setiap hari.\n\nJelajahi koleksi gratis kami — konten dewasa pilihan tanpa komitmen. Gabung channel dan mulai browsing sesuka hati.\n\n✅ Tanpa bayar\n✅ Konten segar hampir setiap hari\n✅ Komunitas rahasia & ramah',
        "premium_title": '👑 *Premium*',
        "premium_body": 'Pass akses penuh ke pengalaman lengkap:\n\n💬 *Grup Premium* — terhubung dan tetap update\n🔗 *Link Tanpa Batas Selamanya* — akses permanen dari exchange\n🌐 *Jalur Premium Situs* — akses premium penuh\n\n━━━━━━━━━━━━━━━━━━━━\n\nMinta bergabung ke channel premium di bawah.\n\nUntuk harga dan pembelian langsung dari admin, hubungi @{owner}.',
        "btn_join_premium": '📺 Minta Bergabung Channel Premium',
        "btn_request_permission": '🔑 Minta Izin Premium',
        "bundles_title": '📦 *Paket Premium*',
        "bundles_body": '📦 *Yang termasuk:* Konten custom berdasarkan fetish dan fantasi Anda.\n\nJujur saja — perpustakaan kami sangat besar, dan dengan database sebesar ini, kategorisasi sempurna tidak selalu mudah. Tetap kami janjikan memilih dan mengirimkan yang terbaik sesuai *permintaan* Anda.\n\nKami tidak pakai link Mega atau cloud dump yang tidak stabil. Layanan itu down, link mati, dan uang Anda terbuang. Kami fokus pada delivery yang curated dan reliable.\n\nCeritakan apa yang Anda cari — hubungi admin di bawah dan buat paket Anda bersama.',
        "btn_request_join_exchange": '📝 Minta Bergabung',
        "btn_verify_exchange_admin": '✅ Verifikasi dengan Admin',
        "exchange_title": '🔄 *Hub Tukar Gratis*',
        "exchange_body": 'Komunitas gratis untuk berbagi dan *ngobrol dengan orang sefrekuensi*.\n\nTukar, diskusi, dan terhubung dengan member yang memiliki minat sama.\n\nSaat ini bergabung *hanya dengan persetujuan*. Kami ingin memastikan Anda punya cukup untuk dibagikan dan sopan kepada semua orang.\n\nMinta bergabung ke grup di bawah, atau verifikasi dengan admin exchange (@{exchange_admin}).',
        "image_title": '🔞 *Morphing Gambar NSFW*\n💳 *Ini adalah layanan berbayar.*',
        "image_body": 'Morphing NSFW custom sesuai *fantasi* kamu — skenario atau gaya apapun:\n\n• Tanpa pakaian / look telanjang\n• Posisi & pose spesifik\n• Outfit, lingerie, atau dress bertema\n• Gaya JOI & permintaan personal lainnya\n• Dan lainnya — ceritakan imajinasimu\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *Layanan baru:* Baru diluncurkan. Kirim satu foto referensi plus brief — outfit, pose, setting — kami morph sesuai keinginanmu.\n\nSiap? Hubungi admin di bawah.',
        "pb_menu": '💎 *Premium & Paket*\n\nPilih opsi di bawah:',
        "help": 'ℹ️ *Bantuan*\n\nGunakan /start untuk memulai atau /menu untuk kembali ke menu utama.\n\nButuh bantuan? Hubungi @{owner}',
        "notify_premium": '🔔 Permintaan Akses Premium',
        "notify_bundles": '🔔 Permintaan Akses Paket',
        "notify_exchange": '🔔 Permintaan Keanggotaan Hub Pertukaran',
        "notify_image": '🔔 Permintaan Morphing NSFW',
        "notify_sent": '✅ Permintaanmu telah dikirim. Kami akan segera menghubungi.'
    },
    "pl":     {
        "language_pick": '🌍 *Język*\n\nWybierz preferowany język:',
        "welcome": '👋 *Witaj, {name}!*\n\nOdkrywaj nasze usługi we własnym tempie! Oferujemy fantastyczne darmowe doświadczenie, abyś mógł poznać naszą ofertę przed podjęciem decyzji.\n\n🌍 *Wybierz język:*',
        "main_menu": '🖤 *Menu Główne*\n\nWybierz usługę, aby dowiedzieć się o niej i uzyskać dostęp:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Dyskretnie · Premium wyselekcjonowane doświadczenia\n🎁 *Nowy tutaj?* Zacznij od Darmowego — odkrywaj, zanim się zdecydujesz.',
        "btn_free": '🆓 Darmowy Dostęp',
        "btn_premium_bundles": '💎 Premium i Pakiety',
        "btn_exchange": '🔄 Darmowy Hub Wymiany',
        "btn_image": '🔞 Morphing NSFW',
        "btn_support": '💬 Wsparcie',
        "btn_change_lang": '🌍 Język',
        "btn_premium": '👑 Premium',
        "btn_bundles": '📦 Pakiety',
        "btn_join_channel": '📢 Dołącz do Kanału',
        "btn_request_access": '🔑 Poproś o Dostęp',
        "btn_request_membership": '📝 Poproś o Członkostwo',
        "btn_verify_admin": '✅ Zweryfikuj u Admina',
        "btn_contact_admin": '💬 Kontakt z Adminem',
        "btn_back_menu": '◀️ Powrót do Menu',
        "btn_back_pb": '◀️ Wstecz',
        "free_title": '🆓 *Darmowy Dostęp*',
        "free_body": 'Stale działająca strona z nowym darmowym contentem prawie codziennie.\n\nOdkryj naszą darmową kolekcję — wyselekcjonowane treści dla dorosłych bez zobowiązań. Dołącz do kanału i przeglądaj we własnym tempie.\n\n✅ Bez płatności\n✅ Świeże treści prawie codziennie\n✅ Dyskretna i przyjazna społeczność',
        "premium_title": '👑 *Premium*',
        "premium_body": 'Twój pełny dostęp do całego doświadczenia:\n\n💬 *Grupa Premium* — rozmawiaj i bądź na bieżąco\n🔗 *Nieograniczone Linki na Zawsze* — stały dostęp z exchange\n🌐 *Ścieżka Premium* — pełny dostęp premium\n\n━━━━━━━━━━━━━━━━━━━━\n\nPoproś o dołączenie do kanału premium poniżej.\n\nCeny i osobisty zakup u admina — napisz do @{owner}.',
        "btn_join_premium": '📺 Poproś o Dołączenie do Kanału Premium',
        "btn_request_permission": '🔑 Poproś o Pozwolenie Premium',
        "bundles_title": '📦 *Pakiety Premium*',
        "bundles_body": '📦 *Co zawiera:* Treści na zamówienie według Twoich fetyszy i fantazji.\n\nSzczerze — nasza biblioteka jest ogromna i przy takiej bazie idealna kategoryzacja nie zawsze jest łatwa. Mimo to obiecujemy wybrać i dostarczyć to, co najlepsze, dopasowane do *Twoich* próśb.\n\nNie używamy linków Mega ani niestabilnych cloud dumpów. Te serwisy padają, linki umierają, a Twoje pieniądze przepadają. U nas dostajesz kuratorowane, niezawodne treści.\n\nPowiedz, czego szukasz — skontaktuj się z adminem poniżej i stwórzmy Twój pakiet.',
        "btn_request_join_exchange": '📝 Poproś o Dołączenie',
        "btn_verify_exchange_admin": '✅ Weryfikuj u Admina',
        "exchange_title": '🔄 *Darmowy Hub Wymiany*',
        "exchange_body": 'Darmowa społeczność do dzielenia się i *rozmowy z podobnie myślącymi*.\n\nWymieniaj się, dyskutuj i łącz z członkami o podobnych zainteresowaniach.\n\nObecnie dołączenie *tylko za zgodą*. Chcemy upewnić się, że masz co dzielić się i jesteś szanujący wobec innych.\n\nPoproś o dołączenie do grupy poniżej lub zweryfikuj u admina exchange (@{exchange_admin}).',
        "image_title": '🔞 *Morphing Obrazów NSFW*\n💳 *To jest usługa płatna.*',
        "image_body": 'Indywidualny morphing NSFW według *twojej* fantazji — każdy scenariusz lub styl:\n\n• Bez ubrań / nago\n• Konkretne pozycje i pozy\n• Stroje, bielizna lub themed dress\n• Styl JOI i inne personalne prośby\n• I więcej — powiedz, co sobie wyobrażasz\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *Nowa usługa:* Właśnie uruchomiona. Wyślij zdjęcie referencyjne plus brief — strój, poza, setting — zmorphujemy dokładnie jak chcesz.\n\nGotowy? Skontaktuj się z adminem poniżej.',
        "pb_menu": '💎 *Premium i Pakiety*\n\nWybierz opcję poniżej:',
        "help": 'ℹ️ *Pomoc*\n\nUżyj /start, aby rozpocząć, lub /menu, aby wrócić do menu głównego.\n\nPotrzebujesz pomocy? Skontaktuj się @{owner}',
        "notify_premium": '🔔 Prośba o Dostęp Premium',
        "notify_bundles": '🔔 Prośba o Dostęp do Pakietów',
        "notify_exchange": '🔔 Prośba o Członkostwo w Hub Wymiany',
        "notify_image": '🔔 Zapytanie Morphing NSFW',
        "notify_sent": '✅ Twoja prośba została wysłana. Wkrótce się skontaktujemy.'
    },
    "nl":     {
        "language_pick": '🌍 *Taal*\n\nSelecteer je voorkeurstaal:',
        "welcome": '👋 *Welkom, {name}!*\n\nVerken onze diensten op je eigen tempo! We bieden een fantastische gratis ervaring zodat je kunt proeven wat we te bieden hebben voordat je een beslissing neemt.\n\n🌍 *Kies je taal:*',
        "main_menu": '🖤 *Hoofdmenu*\n\nSelecteer een dienst om meer te leren en toegang te krijgen:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Discreet · Premium geselecteerde ervaringen\n🎁 *Nieuw hier?* Begin met Gratis — verken voordat je je vastlegt.',
        "btn_free": '🆓 Gratis Toegang',
        "btn_premium_bundles": '💎 Premium & Bundels',
        "btn_exchange": '🔄 Gratis Uitwissel Hub',
        "btn_image": '🔞 NSFW Beeld Morphing',
        "btn_support": '💬 Ondersteuning',
        "btn_change_lang": '🌍 Taal',
        "btn_premium": '👑 Premium',
        "btn_bundles": '📦 Bundels',
        "btn_join_channel": '📢 Word Lid van Kanaal',
        "btn_request_access": '🔑 Toegang Aanvragen',
        "btn_request_membership": '📝 Lidmaatschap Aanvragen',
        "btn_verify_admin": '✅ Verifiëren bij Admin',
        "btn_contact_admin": '💬 Contact Admin',
        "btn_back_menu": '◀️ Terug naar Menu',
        "btn_back_pb": '◀️ Terug',
        "free_title": '🆓 *Gratis Toegang*',
        "free_body": 'Een continu draaiende site met bijna dagelijks nieuwe gratis content.\n\nVerken onze gratis collectie — geselecteerde content voor volwassenen zonder verplichting. Word lid van het kanaal en browse op je eigen tempo.\n\n✅ Geen betaling\n✅ Bijna dagelijks verse content\n✅ Discreet & vriendelijke community',
        "premium_title": '👑 *Premium*',
        "premium_body": 'Jouw all-access pass voor de volledige ervaring:\n\n💬 *Premium Groepschat* — verbinden en op de hoogte blijven\n🔗 *Onbeperkte Links Voor Altijd* — permanente toegang uit de exchange\n🌐 *Premium Site Pad* — volledige premium toegang\n\n━━━━━━━━━━━━━━━━━━━━\n\nVraag hieronder toegang tot het premium kanaal aan.\n\nVoor prijzen en persoonlijke aankoop via admin, contact @{owner}.',
        "btn_join_premium": '📺 Verzoek om Premium Kanaal te Joinen',
        "btn_request_permission": '🔑 Toestemming voor Premium Vragen',
        "bundles_title": '📦 *Premium Bundels*',
        "bundles_body": '📦 *Wat is inbegrepen:* Custom content op basis van jouw fetishes en fantasieën.\n\nEerlijk gezegd — onze bibliotheek is enorm en met een database van deze omvang is perfect categoriseren niet altijd makkelijk. Toch beloven we het beste handmatig te selecteren voor wat *jij* vraagt.\n\nGeen Mega-links of onbetrouwbare cloud dumps. Die diensten gaan offline, links sterven en je geld is weg. Wij bieden gecureerd, betrouwbaar en duurzaam.\n\nVertel ons wat je zoekt — neem contact op met admin hieronder en bouw je bundel samen.',
        "btn_request_join_exchange": '📝 Verzoek om Toegang',
        "btn_verify_exchange_admin": '✅ Verifieer bij Admin',
        "exchange_title": '🔄 *Gratis Uitwissel Hub*',
        "exchange_body": 'Een gratis community om te delen en *te chatten met gelijkgestemden*.\n\nWissel uit, bespreek en verbind met leden die je interesses delen.\n\nMomenteel is toegang *alleen op goedkeuring*. We willen zeker weten dat je genoeg te delen hebt en respectvol bent tegenover iedereen.\n\nVraag hieronder toegang tot de groep, of verifieer bij onze exchange admin (@{exchange_admin}).',
        "image_title": '🔞 *NSFW Beeld Morphing*\n💳 *Dit is een betaalde service.*',
        "image_body": 'Custom NSFW morphing rond *jouw* fantasie — elk scenario of stijl:\n\n• Geen kleding / naakte looks\n• Specifieke posities & houdingen\n• Outfits, lingerie of themed dress\n• JOI-stijl en andere persoonlijke verzoeken\n• En meer — vertel wat je voor je ziet\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *Nieuwe service:* Net gelanceerd. Stuur één referentiefoto plus brief — outfit, pose, setting — wij morphen het precies zoals jij wilt.\n\nKlaar? Neem contact op met admin hieronder.',
        "pb_menu": '💎 *Premium & Bundels*\n\nKies een optie hieronder:',
        "help": 'ℹ️ *Help*\n\nGebruik /start om te beginnen of /menu om terug te gaan naar het hoofdmenu.\n\nHulp nodig? Neem contact op @{owner}',
        "notify_premium": '🔔 Premium Toegang Aanvraag',
        "notify_bundles": '🔔 Bundel Toegang Aanvraag',
        "notify_exchange": '🔔 Uitwisselingshub Lidmaatschap Aanvraag',
        "notify_image": '🔔 NSFW Morphing Aanvraag',
        "notify_sent": '✅ Je aanvraag is verzonden. We nemen binnenkort contact op.'
    },
    "ja":     {
        "language_pick": '🌍 *言語*\n\n希望の言語を選択してください:',
        "welcome": '👋 *ようこそ、{name}さん！*\n\nご自身のペースでサービスをお試しください！決める前に当社の内容を体験できる、素晴らしい無料体験をご用意しています。\n\n🌍 *言語を選択：*',
        "main_menu": '🖤 *メインメニュー*\n\nサービスを選んで詳細を確認し、アクセスしてください：',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* ·  discreet · 厳選プレミアム体験\n🎁 *初めての方？* 無料から始めて — 決める前に探索しましょう。',
        "btn_free": '🆓 無料アクセス',
        "btn_premium_bundles": '💎 プレミアム＆バンドル',
        "btn_exchange": '🔄 無料交換ハブ',
        "btn_image": '🔞 NSFW画像モーフィング',
        "btn_support": '💬 サポート',
        "btn_change_lang": '🌍 言語',
        "btn_premium": '💎 プレミアム',
        "btn_bundles": '📦 バンドル',
        "btn_join_channel": '📢 チャンネル参加',
        "btn_request_access": '🔑 アクセス申請',
        "btn_request_membership": '📝 メンバーシップ申請',
        "btn_verify_admin": '✅ 管理者確認',
        "btn_contact_admin": '💬 管理者に連絡',
        "btn_back_menu": '◀️ メニューに戻る',
        "btn_back_pb": '◀️ 戻る',
        "free_title": '🆓 *無料アクセス*',
        "free_body": 'ほぼ毎日新しい無料コンテンツを追加する、常時稼働のサイト。\n\n無料コレクションをお試しください — コミットメント不要の厳選アダルトコンテンツ。 下のチャンネルに参加して、自分のペースで閲覧できます。\n\n✅ 支払い不要\n✅ ほぼ毎日新着\n✅ プライベートでフレンドリーなコミュニティ',
        "premium_title": '👑 *プレミアム*',
        "premium_body": 'フル体験へのオールアクセスパス：\n\n💬 *プレミアムグループ* — チャットと交流\n🔗 *永久無制限リンク* — exchangeの永久アクセス\n🌐 *プレミアムサイトパス* — フルプレミアム体験\n\n━━━━━━━━━━━━━━━━━━━━\n\n下からプレミアムチャンネルへの参加をリクエストしてください。\n\n価格と管理者からの個人購入は @{owner} まで。',
        "btn_join_premium": '📺 プレミアムチャンネル参加をリクエスト',
        "btn_request_permission": '🔑 プレミアム許可をリクエスト',
        "bundles_title": '📦 *プレミアムバンドル*',
        "bundles_body": '📦 *含まれるもの:* あなたのフェチやファンタジーに基づくカスタムコンテンツ。\n\n正直に言うと — ライブラリは巨大で、この規模のデータベースでは完璧な分類が常に可能とは限りません。それでも*あなた*のリクエストに合わせ、最高のものを厳選してお届けすることをお約束します。\n\nMegaリンクや不安定なクラウドダンプは使いません。サービスが落ち、リンクが切れ、お金が無駄になるからです。私たちはキュレーションされた信頼できる配信を提供します。\n\nご希望をお聞かせください — 下の管理者に連絡して、一緒にバンドルを作りましょう。',
        "btn_request_join_exchange": '📝 参加をリクエスト',
        "btn_verify_exchange_admin": '✅ 管理者に確認',
        "exchange_title": '🔄 *無料交換ハブ*',
        "exchange_body": '共有と*同じ志を持つ人とのチャット*のための無料コミュニティ。\n\n興味を共有するメンバーと交換・議論・交流できます。\n\n現在、参加は*承認制のみ*です。共有できる内容があり、コミュニティに敬意を持てる方のみご参加ください。\n\n下からグループ参加をリクエストするか、exchange管理者 (@{exchange_admin}) に確認してください。',
        "image_title": '🔞 *NSFW画像モーフィング*\n💳 *有料サービスです。*',
        "image_body": '*あなた*のファンタジーに合わせたカスタムNSFWモーフィング — あらゆるシーンやスタイル：\n\n• ノードレス / ヌード\n• 特定のポーズ・体位\n• 衣装、ランジェリー、テーマドレス\n• JOIスタイルなどパーソナルリクエスト\n• その他 — イメージを教えてください\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *新サービス:* 開始しました。参考写真1枚とブリーフ — 衣装、ポーズ、設定 — を送ってください。希望通りにモーフィングします。\n\n準備OK？下の管理者に連絡してください。',
        "pb_menu": '💎 *プレミアム＆バンドル*\n\n下からオプションを選択：',
        "help": 'ℹ️ *ヘルプ*\n\n/start で開始、/menu でメインメニューに戻ります。\n\nサポートが必要ですか？ @{owner} に連絡',
        "notify_premium": '🔔 プレミアムアクセス申請',
        "notify_bundles": '🔔 バンドルアクセス申請',
        "notify_exchange": '🔔 交換ハブメンバーシップ申請',
        "notify_image": '🔞 NSFWモーフィング問い合わせ',
        "notify_sent": '✅ 申請が送信されました。まもなくご連絡いたします。'
    },
    "ko":     {
        "language_pick": '🌍 *언어*\n\n원하는 언어를 선택하세요:',
        "welcome": '👋 *환영합니다, {name}님!*\n\n편한 속도로 서비스를 둘러보세요! 결정하기 전에 우리가 제공하는 것을 경험할 수 있는 훌륭한 무료 체험을 제공합니다.\n\n🌍 *언어를 선택하세요:*',
        "main_menu": '🖤 *메인 메뉴*\n\n서비스를 선택하여 알아보고 이용하세요:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · 은밀 · 프리미엄 큐레이션 경험\n🎁 *처음이신가요?* 무료로 시작 — 결정 전에 탐색하세요.',
        "btn_free": '🆓 무료 이용',
        "btn_premium_bundles": '💎 프리미엄 & 번들',
        "btn_exchange": '🔄 무료 교환 허브',
        "btn_image": '🔞 NSFW 이미지 모핑',
        "btn_support": '💬 지원',
        "btn_change_lang": '🌍 언어',
        "btn_premium": '💎 프리미엄',
        "btn_bundles": '📦 번들',
        "btn_join_channel": '📢 채널 참가',
        "btn_request_access": '🔑 접근 요청',
        "btn_request_membership": '📝 멤버십 요청',
        "btn_verify_admin": '✅ 관리자 확인',
        "btn_contact_admin": '💬 관리자 연락',
        "btn_back_menu": '◀️ 메뉴로 돌아가기',
        "btn_back_pb": '◀️ 뒤로',
        "free_title": '🆓 *무료 이용*',
        "free_body": '거의 매일 새로운 무료 콘텐츠를 제공하는 상시 운영 사이트.\n\n무료 컬렉션을 둘러보세요 — 부담 없는 엄선된 성인 콘텐츠. 아래 채널에 가입하고 편한 속도로 즐기세요.\n\n✅ 결제 불필요\n✅ 거의 매일 새 콘텐츠\n✅ 비공개 & 친근한 커뮤니티',
        "premium_title": '👑 *프리미엄*',
        "premium_body": '전체 경험을 위한 올액세스 패스:\n\n💬 *프리미엄 그룹* — 채팅과 소통\n🔗 *영구 무제한 링크* — exchange 영구 접근\n🌐 *프리미엄 사이트 경로* — 전체 프리미엄 이용\n\n━━━━━━━━━━━━━━━━━━━━\n\n아래에서 프리미엄 채널 가입을 요청하세요.\n\n가격 및 관리자 직접 구매는 @{owner}에게 문의하세요.',
        "btn_join_premium": '📺 프리미엄 채널 가입 요청',
        "btn_request_permission": '🔑 프리미엄 권한 요청',
        "bundles_title": '📦 *프리미엄 번들*',
        "bundles_body": '📦 *포함 내용:* 페티시와 판타지에 맞춘 맞춤 콘텐츠.\n\n솔직히 말씀드리면 — 라이브러리가 방대해서 이 규모의 데이터베이스에서는 완벽한 분류가 항상 쉽지 않습니다. 그래도 *당신*의 요청에 맞춰 최고의 콘텐츠를 엄선해 전달하겠습니다.\n\nMega 링크나 불안정한 클라우드 덤프는 사용하지 않습니다. 서비스가 중단되고 링크가 끊기면 돈이 낭비됩니다. 저희는 큐레이션된 신뢰할 수 있는 전달을 제공합니다.\n\n원하시는 것을 알려주세요 — 아래 관리자에게 연락해 함께 번들을 만들어 보세요.',
        "btn_request_join_exchange": '📝 가입 요청',
        "btn_verify_exchange_admin": '✅ 관리자 확인',
        "exchange_title": '🔄 *무료 교환 허브*',
        "exchange_body": '공유하고 *같은 관심사를 가진 사람들과 채팅*하는 무료 커뮤니티.\n\n관심사를 공유하는 회원들과 교환, 토론, 교류하세요.\n\n현재 가입은 *승인제*입니다. 공유할 충분한 콘텐츠가 있고 모두에게 존중하는지 확인합니다.\n\n아래에서 그룹 가입을 요청하거나 exchange 관리자 (@{exchange_admin})에게 확인하세요.',
        "image_title": '🔞 *NSFW 이미지 모핑*\n💳 *유료 서비스입니다.*',
        "image_body": '*당신*의 판타지에 맞춘 맞춤 NSFW 모핑 — 모든 시나리오와 스타일:\n\n• 노드레스 / 누드\n• 특정 포즈와 자세\n• 의상, 란제리, 테마 드레스\n• JOI 스타일 및 맞춤 요청\n• 그 외 — 상상하는 것을 알려주세요\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *신규 서비스:* 방금 시작했습니다. 참조 사진 1장과 브리프 — 의상, 포즈, 설정 — 를 보내주시면 원하는 대로 모핑합니다.\n\n준비되셨나요? 아래 관리자에게 연락하세요.',
        "pb_menu": '💎 *프리미엄 & 번들*\n\n아래에서 옵션 선택:',
        "help": 'ℹ️ *도움말*\n\n/start로 시작하거나 /menu로 메인 메뉴로 돌아갑니다.\n\n도움이 필요하신가요? @{owner}에게 연락',
        "notify_premium": '🔔 프리미엄 접근 요청',
        "notify_bundles": '🔔 번들 접근 요청',
        "notify_exchange": '🔔 교환 허브 멤버십 요청',
        "notify_image": '🔔 NSFW 모핑 문의',
        "notify_sent": '✅ 요청이 전송되었습니다. 곧 연락드리겠습니다.'
    },
    "zh":     {
        "language_pick": '🌍 *语言*\n\n选择您的首选语言:',
        "welcome": '👋 *欢迎，{name}！*\n\n请按自己的节奏探索我们的服务！我们提供精彩的免费体验，让您在做出决定前先了解我们的内容。\n\n🌍 *选择语言：*',
        "main_menu": '🖤 *主菜单*\n\n选择一项服务以了解并访问：',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · 私密 · 精选 premium 体验\n🎁 *新来的？* 从免费开始 — 决定前先探索。',
        "btn_free": '🆓 免费访问',
        "btn_premium_bundles": '💎 高级与套餐',
        "btn_exchange": '🔄 免费交换中心',
        "btn_image": '🔞 NSFW图像变形',
        "btn_support": '💬 支持',
        "btn_change_lang": '🌍 语言',
        "btn_premium": '💎 高级',
        "btn_bundles": '📦 套餐',
        "btn_join_channel": '📢 加入频道',
        "btn_request_access": '🔑 申请访问',
        "btn_request_membership": '📝 申请会员',
        "btn_verify_admin": '✅ 管理员验证',
        "btn_contact_admin": '💬 联系管理员',
        "btn_back_menu": '◀️ 返回菜单',
        "btn_back_pb": '◀️ 返回',
        "free_title": '🆓 *免费访问*',
        "free_body": '持续运行的站点，几乎每天都有新的免费内容。\n\n探索我们的免费合集 — 精选成人内容，无需任何承诺。 加入下方频道，按自己的节奏浏览。\n\n✅ 无需付款\n✅ 几乎每日更新\n✅ 私密友好的社区',
        "premium_title": '👑 *高级会员*',
        "premium_body": '全方位体验通行证：\n\n💬 *高级群组* — 聊天与交流\n🔗 *永久无限链接* — exchange永久访问\n🌐 *高级站点通道* — 完整高级体验\n\n━━━━━━━━━━━━━━━━━━━━\n\n请在下方请求加入高级频道。\n\n了解价格并直接向管理员购买，请联系 @{owner}。',
        "btn_join_premium": '📺 请求加入高级频道',
        "btn_request_permission": '🔑 请求高级权限',
        "bundles_title": '📦 *高级套餐*',
        "bundles_body": '📦 *包含内容:* 根据您的癖好和幻想定制的专属内容。\n\n实话实说 — 我们的库非常庞大，数据库这么大，完美分类并不总是容易。但我们仍承诺根据*您的*需求精心挑选并交付最优质的内容。\n\n我们不使用 Mega 链接或不可靠的云盘。那些服务会下线，链接会失效，您的钱就白费了。我们提供精心策划、可靠持久的交付。\n\n告诉我们您想要什么 — 联系下方管理员，一起打造您的套餐。',
        "btn_request_join_exchange": '📝 请求加入',
        "btn_verify_exchange_admin": '✅ 管理员验证',
        "exchange_title": '🔄 *免费交换中心*',
        "exchange_body": '免费社区，用于分享和*与志同道合的人聊天*。\n\n与兴趣相同的成员交换、讨论和连接。\n\n目前加入*仅限批准*。我们希望确保您有足够的内容分享 并对社区成员保持尊重。\n\n请在下方请求加入群组，或联系 exchange 管理员 (@{exchange_admin}) 验证。',
        "image_title": '🔞 *NSFW图像变形*\n💳 *这是付费服务。*',
        "image_body": '根据*您的*幻想定制NSFW变形 — 任何场景或风格：\n\n• 无衣 / 裸体造型\n• 特定姿势与体位\n• 服装、内衣或主题穿着\n• JOI风格及其他个性化请求\n• 更多 — 告诉我们您的想象\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *新服务：* 刚刚推出。发送一张参考照片和说明 — 服装、姿势、场景 — 我们按您的要求变形。\n\n准备好了？联系下方管理员。',
        "pb_menu": '💎 *高级与套餐*\n\n请在下方选择：',
        "help": 'ℹ️ *帮助*\n\n使用 /start 开始或 /menu 返回主菜单。\n\n需要帮助？联系 @{owner}',
        "notify_premium": '🔔 高级访问申请',
        "notify_bundles": '🔔 套餐访问申请',
        "notify_exchange": '🔔 交换中心会员申请',
        "notify_image": '🔔 NSFW变形咨询',
        "notify_sent": '✅ 您的申请已发送。我们将很快与您联系。'
    },
    "uk":     {
        "language_pick": '🌍 *Мова*\n\nОберіть бажану мову:',
        "welcome": '👋 *Ласкаво просимо, {name}!*\n\nДосліджуйте наші сервіси у власному темпі! Ми пропонуємо чудовий безкоштовний досвід, щоб ви могли оцінити наші можливості перед прийняттям рішення.\n\n🌍 *Оберіть мову:*',
        "main_menu": '🖤 *Головне меню*\n\nОберіть сервіс, щоб дізнатися про нього та отримати доступ:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Конфіденційно · Преміальний відбір контенту\n🎁 *Вперше тут?* Почніть з Безкоштовного — досліджуйте, перш ніж вирішити.',
        "btn_free": '🆓 Безкоштовний доступ',
        "btn_premium_bundles": '💎 Преміум і Пакети',
        "btn_exchange": '🔄 Безкоштовний Хаб Обміну',
        "btn_image": '🔞 NSFW Морфінг',
        "btn_support": '💬 Підтримка',
        "btn_change_lang": '🌍 Мова',
        "btn_premium": '💎 Преміум',
        "btn_bundles": '📦 Пакети',
        "btn_join_channel": '📢 Приєднатися до Каналу',
        "btn_request_access": '🔑 Запросити Доступ',
        "btn_request_membership": '📝 Запросити Членство',
        "btn_verify_admin": '✅ Підтвердити в Адміна',
        "btn_contact_admin": "💬 Зв'язатися з Адміном",
        "btn_back_menu": '◀️ До головного меню',
        "btn_back_pb": '◀️ Назад',
        "free_title": '🆓 *Безкоштовний доступ*',
        "free_body": "Постійно працюючий сайт із новим безкоштовним контентом майже щодня.\n\nДосліджуйте нашу безкоштовну колекцію — відібраний контент для дорослих без зобов'язань. Приєднуйтесь до каналу та переглядайте у своєму темпі.\n\n✅ Без оплати\n✅ Свіжий контент майже щодня\n✅ Конфіденційна спільнота",
        "premium_title": '👑 *Преміум*',
        "premium_body": 'Ваш повний доступ до всього досвіду:\n\n💬 *Преміум-група* — спілкуйтеся та будьте в курсі\n🔗 *Необмежені посилання назавжди* — постійний доступ з exchange\n🌐 *Преміум-шлях на сайті* — повний преміум-доступ\n\n━━━━━━━━━━━━━━━━━━━━\n\nЗапросіть вступ до преміум-каналу нижче.\n\nЦіни та особиста покупка у адміна — @{owner}.',
        "btn_join_premium": '📺 Запит на Вступ до Преміум-каналу',
        "btn_request_permission": '🔑 Запросити Дозвіл на Premium',
        "bundles_title": '📦 *Преміум Пакети*',
        "bundles_body": '📦 *Що входить:* Індивідуальний контент за вашими фетишами та фантазіями.\n\nЧесно кажучи — наша бібліотека величезна, і при такій базі ідеальна категоризація не завжди можлива. Але ми обіцяємо відібрати та доставити найкраще під *ваші* запити.\n\nМи не використовуємо Mega-посилання чи ненадійні хмари. Сервіси падають, посилання вмирають — і ваші гроші зникають. У нас — курований, надійний контент.\n\nРозкажіть, що шукаєте — напишіть адміну нижче, і зберемо ваш пакет разом.',
        "btn_request_join_exchange": '📝 Запит на Вступ',
        "btn_verify_exchange_admin": '✅ Підтвердити у Адміна',
        "exchange_title": '🔄 *Безкоштовний Хаб Обміну*',
        "exchange_body": "Безкоштовна спільнота для обміну та *спілкування з однодумцями*.\n\nОбмінюйтеся, обговорюйте та спілкуйтеся з учасниками, які поділяють ваші інтереси.\n\nЗараз вступ *лише за схваленням*. Ми хочемо переконатися, що у вас є чим поділитися і ви поважаєте спільноту.\n\nЗапросіть вступ до групи нижче або зв'яжіться з admin exchange (@{exchange_admin}).",
        "image_title": '🔞 *NSFW Морфінг Зображень*\n💳 *Це платний сервіс.*',
        "image_body": 'Індивідуальний NSFW-морфінг під *вашу* фантазію — будь-який сценарій або стиль:\n\n• Без одягу / оголені образи\n• Конкретні пози та положення\n• Наряди, білизна або themed dress\n• JOI та інші персональні запити\n• І більше — опишіть, що уявляєте\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *Новий сервіс:* Щойно запустили. Надішліть референс-фото та опис — наряд, поза, обстановка — зробимо морфінг як ви хочете.\n\nГотові? Напишіть адміну нижче.',
        "pb_menu": '💎 *Преміум і Пакети*\n\nОберіть варіант нижче:',
        "help": "ℹ️ *Допомога*\n\nВикористовуйте /start для початку або /menu для повернення до головного меню.\n\nПотрібна допомога? Зв'яжіться @{owner}",
        "notify_premium": '🔔 Запит Преміум Доступу',
        "notify_bundles": '🔔 Запит Доступу до Пакетів',
        "notify_exchange": '🔔 Запит Членства в Хабі Обміну',
        "notify_image": '🔔 Запит NSFW Морфінг',
        "notify_sent": "✅ Ваш запит надіслано. Ми скоро зв'яжемося з вами."
    },
    "vi":     {
        "language_pick": '🌍 *Ngôn ngữ*\n\nChọn ngôn ngữ ưa thích:',
        "welcome": '👋 *Chào mừng, {name}!*\n\nHãy khám phá dịch vụ của chúng tôi theo nhịp độ của bạn! Chúng tôi cung cấp trải nghiệm miễn phí tuyệt vời để bạn cảm nhận những gì chúng tôi có trước khi quyết định.\n\n🌍 *Chọn ngôn ngữ:*',
        "main_menu": '🖤 *Menu Chính*\n\nChọn dịch vụ để tìm hiểu và truy cập:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · Kín đáo · Trải nghiệm premium được tuyển chọn\n🎁 *Mới đến?* Bắt đầu với Miễn phí — khám phá trước khi cam kết.',
        "btn_free": '🆓 Truy cập Miễn phí',
        "btn_premium_bundles": '💎 Premium & Gói',
        "btn_exchange": '🔄 Hub Trao Đổi Miễn Phí',
        "btn_image": '🔞 Morphing NSFW',
        "btn_support": '💬 Hỗ trợ',
        "btn_change_lang": '🌍 Ngôn ngữ',
        "btn_premium": '👑 Premium',
        "btn_bundles": '📦 Gói',
        "btn_join_channel": '📢 Tham gia Kênh',
        "btn_request_access": '🔑 Yêu cầu Truy cập',
        "btn_request_membership": '📝 Yêu cầu Thành viên',
        "btn_verify_admin": '✅ Xác minh với Admin',
        "btn_contact_admin": '💬 Liên hệ Admin',
        "btn_back_menu": '◀️ Về Menu',
        "btn_back_pb": '◀️ Quay lại',
        "free_title": '🆓 *Truy cập Miễn phí*',
        "free_body": 'Trang web chạy liên tục với nội dung miễn phí mới gần như mỗi ngày.\n\nKhám phá bộ sưu tập miễn phí — nội dung người lớn được chọn lọc, không ràng buộc. Tham gia kênh bên dưới và duyệt theo nhịp độ của bạn.\n\n✅ Không cần thanh toán\n✅ Nội dung mới gần như hàng ngày\n✅ Cộng đồng riêng tư & thân thiện',
        "premium_title": '👑 *Premium*',
        "premium_body": 'Pass truy cập toàn diện:\n\n💬 *Nhóm Premium* — trò chuyện và kết nối\n🔗 *Liên kết Không giới hạn Mãi mãi* — truy cập vĩnh viễn từ exchange\n🌐 *Lối Premium trên Site* — truy cập premium đầy đủ\n\n━━━━━━━━━━━━━━━━━━━━\n\nYêu cầu tham gia kênh premium bên dưới.\n\nXem giá và mua trực tiếp từ admin, liên hệ @{owner}.',
        "btn_join_premium": '📺 Yêu cầu Tham gia Kênh Premium',
        "btn_request_permission": '🔑 Yêu cầu Quyền Premium',
        "bundles_title": '📦 *Gói Premium*',
        "bundles_body": '📦 *Bao gồm:* Nội dung tùy chỉnh theo fetish và fantasy của bạn.\n\nThành thật mà nói — thư viện của chúng tôi rất lớn, và với cơ sở dữ liệu khổng lồ này, phân loại hoàn hảo không phải lúc nào cũng dễ. Dù vậy, chúng tôi hứa chọn lọc và giao những gì tốt nhất theo *yêu cầu* của bạn.\n\nChúng tôi không dùng link Mega hay cloud dump không ổn định. Dịch vụ sập, link chết và tiền của bạn mất trắng. Chúng tôi tập trung vào giao hàng curated, đáng tin.\n\nCho biết bạn cần gì — liên hệ admin bên dưới để cùng tạo gói của bạn.',
        "btn_request_join_exchange": '📝 Yêu cầu Tham gia',
        "btn_verify_exchange_admin": '✅ Xác minh với Admin',
        "exchange_title": '🔄 *Hub Trao Đổi Miễn Phí*',
        "exchange_body": 'Cộng đồng miễn phí để chia sẻ và *trò chuyện với những người cùng chí hướng*.\n\nTrao đổi, thảo luận và kết nối với thành viên có cùng sở thích.\n\nHiện tại tham gia *chỉ qua phê duyệt*. Chúng tôi muốn đảm bảo bạn có đủ để chia sẻ và tôn trọng mọi người.\n\nYêu cầu tham gia nhóm bên dưới, hoặc xác minh với admin exchange (@{exchange_admin}).',
        "image_title": '🔞 *Morphing Hình Ảnh NSFW*\n💳 *Đây là dịch vụ trả phí.*',
        "image_body": 'Morphing NSFW tùy chỉnh theo *fantasy* của bạn — mọi kịch bản hoặc phong cách:\n\n• Không mặc / look khỏa thân\n• Tư thế & pose cụ thể\n• Trang phục, nội y hoặc dress theo chủ đề\n• Phong cách JOI & yêu cầu cá nhân khác\n• Và hơn thế — cho biết bạn tưởng tượng gì\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *Dịch vụ mới:* Vừa ra mắt. Gửi một ảnh tham chiếu kèm brief — trang phục, pose, bối cảnh — chúng tôi morph đúng như bạn muốn.\n\nSẵn sàng? Liên hệ admin bên dưới.',
        "pb_menu": '💎 *Premium & Gói*\n\nChọn tùy chọn bên dưới:',
        "help": 'ℹ️ *Trợ giúp*\n\nDùng /start để bắt đầu hoặc /menu để về menu chính.\n\nCần hỗ trợ? Liên hệ @{owner}',
        "notify_premium": '🔔 Yêu cầu Truy cập Premium',
        "notify_bundles": '🔔 Yêu cầu Truy cập Gói',
        "notify_exchange": '🔔 Yêu cầu Thành viên Trung tâm Trao đổi',
        "notify_image": '🔔 Yêu cầu Morphing NSFW',
        "notify_sent": '✅ Yêu cầu của bạn đã được gửi. Chúng tôi sẽ liên hệ sớm.'
    },
    "th":     {
        "language_pick": '🌍 *ภาษา*\n\nเลือกภาษาที่ต้องการ:',
        "welcome": '👋 *ยินดีต้อนรับ, {name}!*\n\nสำรวจบริการของเราได้ตามจังหวะของคุณ! เรามีประสบการณ์ฟรีที่ยอดเยี่ยมให้คุณได้ลองก่อนตัดสินใจ\n\n🌍 *เลือกภาษา:*',
        "main_menu": '🖤 *เมนูหลัก*\n\nเลือกบริการเพื่อเรียนรู้และเข้าถึง:',
        "cta_footer": '\n\n━━━━━━━━━━━━━━━━━━━━\n🔞 *18+* · เป็นส่วนตัว · ประสบการณ์พรีเมียมคัดสรร\n🎁 *มาใหม่?* เริ่มจากฟรี — สำรวจก่อนตัดสินใจ',
        "btn_free": '🆓 เข้าถึงฟรี',
        "btn_premium_bundles": '💎 พรีเมียมและแพ็กเกจ',
        "btn_exchange": '🔄 ศูนย์แลกเปลี่ยนฟรี',
        "btn_image": '🔞 Morphing NSFW',
        "btn_support": '💬 ฝ่ายสนับสนุน',
        "btn_change_lang": '🌍 ภาษา',
        "btn_premium": '💎 พรีเมียม',
        "btn_bundles": '📦 แพ็กเกจ',
        "btn_join_channel": '📢 เข้าร่วมช่อง',
        "btn_request_access": '🔑 ขอการเข้าถึง',
        "btn_request_membership": '📝 ขอสมาชิก',
        "btn_verify_admin": '✅ ยืนยันกับแอดมิน',
        "btn_contact_admin": '💬 ติดต่อแอดมิน',
        "btn_back_menu": '◀️ กลับเมนู',
        "btn_back_pb": '◀️ กลับ',
        "free_title": '🆓 *เข้าถึงฟรี*',
        "free_body": 'เว็บไซต์ที่เปิดตลอด พร้อมคอนเทนต์ฟรีใหม่เกือบทุกวัน\n\nสำรวจคอลเลกชันฟรีของเรา — คอนเทนต์ผู้ใหญ่คัดสรร ไม่มีข้อผูกมัด เข้าร่วมช่องด้านล่างและเริ่มดูตามจังหวะของคุณ\n\n✅ ไม่ต้องจ่าย\n✅ คอนเทนต์ใหม่เกือบทุกวัน\n✅ ชุมชนเป็นส่วนตัวและเป็นมิตร',
        "premium_title": '👑 *พรีเมียม*',
        "premium_body": 'พาสเข้าถึงประสบการณ์เต็มรูปแบบ:\n\n💬 *กลุ่มพรีเมียม* — แชทและเชื่อมต่อ\n🔗 *ลิงก์ไม่จำกัดตลอดไป* — เข้าถึงถาวรจาก exchange\n🌐 *เส้นทางพรีเมียม* — เข้าถึงพรีเมียมครบ\n\n━━━━━━━━━━━━━━━━━━━━\n\nขอเข้าร่วมช่องพรีเมียมด้านล่าง\n\nดูราคาและซื้อจากแอดมินโดยตรง ติดต่อ @{owner}',
        "btn_join_premium": '📺 ขอเข้าร่วมช่องพรีเมียม',
        "btn_request_permission": '🔑 ขออนุญาตพรีเมียม',
        "bundles_title": '📦 *แพ็กเกจพรีเมียม*',
        "bundles_body": '📦 *รวม:* คอนเทนต์ตามคำขอตาม fetish และ fantasy ของคุณ\n\nพูดตรงๆ — ไลบรารีของเราใหญ่มาก และด้วยฐานข้อมูลขนาดนี้ การจัดหมวดหมู่ให้สมบูรณ์แบบ ไม่ใช่เรื่องง่ายเสมอไป แต่เราสัญญาว่าจะคัดสรรและส่งมอบสิ่งที่ดีที่สุดตามที่*คุณ*ต้องการ\n\nเราไม่ใช้ลิงก์ Mega หรือ cloud dump ที่ไม่เสถียร บริการล่ม ลิงก์เสีย และเงินของคุณก็เสียเปล่า เรามุ่งเน้นการส่งมอบที่คัดสรรแล้วและเชื่อถือได้\n\nบอกสิ่งที่คุณต้องการ — ติดต่อแอดมินด้านล่าง แล้วมาสร้างแพ็กของคุณด้วยกัน',
        "btn_request_join_exchange": '📝 ขอเข้าร่วม',
        "btn_verify_exchange_admin": '✅ ยืนยันกับแอดมิน',
        "exchange_title": '🔄 *ศูนย์แลกเปลี่ยนฟรี*',
        "exchange_body": 'ชุมชนฟรีสำหรับแชร์และ*คุยกับคนที่มีความสนใจคล้ายกัน*.\n\nแลกเปลี่ยน อภิปราย และเชื่อมต่อกับสมาชิกที่มีความสนใจร่วมกัน.\n\nปัจจุบันการเข้าร่วม *ต้องได้รับการอนุมัติเท่านั้น* เราต้องการให้แน่ใจว่า คุณมีสิ่งที่จะแชร์เพียงพอและเคารพทุกคนในชุมชน.\n\nขอเข้าร่วมกลุ่มด้านล่าง หรือยืนยันกับ admin exchange (@{exchange_admin}).',
        "image_title": '🔞 *Morphing ภาพ NSFW*\n💳 *นี่เป็นบริการที่มีค่าใช้จ่าย*',
        "image_body": 'Morphing NSFW ตาม *fantasy* ของคุณ — ทุกสcenariо หรือสไตล์:\n\n• ไม่ใส่ชุด / ลุคเปลือย\n• ท่าและ pose เฉพาะ\n• ชุด ชุดชั้นใน หรือ dress ตามธีม\n• สไตล์ JOI และคำขอส่วนตัวอื่นๆ\n• และอื่นๆ — บอกว่าจินตนาการอะไร\n\n━━━━━━━━━━━━━━━━━━━━\n\n✨ *บริการใหม่:* เพิ่งเปิดตัว ส่งรูปอ้างอิง 1 รูปพร้อม brief — ชุด ท่า ฉาก — เราจะ morph ตามที่ต้องการ\n\nพร้อมแล้ว? ติดต่อแอดมินด้านล่าง',
        "pb_menu": '💎 *พรีเมียมและแพ็กเกจ*\n\nเลือกตัวเลือกด้านล่าง:',
        "help": 'ℹ️ *ช่วยเหลือ*\n\nใช้ /start เพื่อเริ่ม หรือ /menu เพื่อกลับเมนูหลัก\n\nต้องการความช่วยเหลือ? ติดต่อ @{owner}',
        "notify_premium": '🔔 คำขอเข้าถึงพรีเมียม',
        "notify_bundles": '🔔 คำขอเข้าถึงแพ็กเกจ',
        "notify_exchange": '🔔 คำขอสมาชิกศูนย์แลกเปลี่ยน',
        "notify_image": '🔔 สอบถาม Morphing NSFW',
        "notify_sent": '✅ ส่งคำขอของคุณแล้ว เราจะติดต่อเร็วๆ นี้'
    }
}


def t(lang: str, key: str, **kwargs) -> str:
    """Return translated string for *lang* and *key*, falling back to English."""
    bundle = TEXTS.get(lang) or TEXTS[DEFAULT_LANG]
    text = bundle.get(key) or TEXTS[DEFAULT_LANG].get(key, key)
    return text.format(**kwargs) if kwargs else text
